/*
secure.scotiabank.com.har Mitmproxy2Swagger

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiCreditCreditIdGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCreditCreditIdGet200Response{}

// ApiCreditCreditIdGet200Response struct for ApiCreditCreditIdGet200Response
type ApiCreditCreditIdGet200Response struct {
	Data *ApiCreditCreditIdGet200ResponseData `json:"data,omitempty"`
	Notifications []interface{} `json:"notifications,omitempty"`
}

// NewApiCreditCreditIdGet200Response instantiates a new ApiCreditCreditIdGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCreditCreditIdGet200Response() *ApiCreditCreditIdGet200Response {
	this := ApiCreditCreditIdGet200Response{}
	return &this
}

// NewApiCreditCreditIdGet200ResponseWithDefaults instantiates a new ApiCreditCreditIdGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCreditCreditIdGet200ResponseWithDefaults() *ApiCreditCreditIdGet200Response {
	this := ApiCreditCreditIdGet200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ApiCreditCreditIdGet200Response) GetData() ApiCreditCreditIdGet200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret ApiCreditCreditIdGet200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreditCreditIdGet200Response) GetDataOk() (*ApiCreditCreditIdGet200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ApiCreditCreditIdGet200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ApiCreditCreditIdGet200ResponseData and assigns it to the Data field.
func (o *ApiCreditCreditIdGet200Response) SetData(v ApiCreditCreditIdGet200ResponseData) {
	o.Data = &v
}

// GetNotifications returns the Notifications field value if set, zero value otherwise.
func (o *ApiCreditCreditIdGet200Response) GetNotifications() []interface{} {
	if o == nil || IsNil(o.Notifications) {
		var ret []interface{}
		return ret
	}
	return o.Notifications
}

// GetNotificationsOk returns a tuple with the Notifications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreditCreditIdGet200Response) GetNotificationsOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.Notifications) {
		return nil, false
	}
	return o.Notifications, true
}

// HasNotifications returns a boolean if a field has been set.
func (o *ApiCreditCreditIdGet200Response) HasNotifications() bool {
	if o != nil && !IsNil(o.Notifications) {
		return true
	}

	return false
}

// SetNotifications gets a reference to the given []interface{} and assigns it to the Notifications field.
func (o *ApiCreditCreditIdGet200Response) SetNotifications(v []interface{}) {
	o.Notifications = v
}

func (o ApiCreditCreditIdGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCreditCreditIdGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Notifications) {
		toSerialize["notifications"] = o.Notifications
	}
	return toSerialize, nil
}

type NullableApiCreditCreditIdGet200Response struct {
	value *ApiCreditCreditIdGet200Response
	isSet bool
}

func (v NullableApiCreditCreditIdGet200Response) Get() *ApiCreditCreditIdGet200Response {
	return v.value
}

func (v *NullableApiCreditCreditIdGet200Response) Set(val *ApiCreditCreditIdGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCreditCreditIdGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCreditCreditIdGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCreditCreditIdGet200Response(val *ApiCreditCreditIdGet200Response) *NullableApiCreditCreditIdGet200Response {
	return &NullableApiCreditCreditIdGet200Response{value: val, isSet: true}
}

func (v NullableApiCreditCreditIdGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCreditCreditIdGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


