/*
secure.scotiabank.com.har Mitmproxy2Swagger

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner{}

// ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner struct for ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner
type ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner struct {
	Key *string `json:"key,omitempty"`
	Id *string `json:"id,omitempty"`
	Description *string `json:"description,omitempty"`
	DescriptionLines map[string]interface{} `json:"descriptionLines,omitempty"`
	SubDescription map[string]interface{} `json:"subDescription,omitempty"`
	CleanDescription map[string]interface{} `json:"cleanDescription,omitempty"`
	MnemonicCode map[string]interface{} `json:"mnemonicCode,omitempty"`
	Type map[string]interface{} `json:"type,omitempty"`
	TsysCode map[string]interface{} `json:"tsysCode,omitempty"`
	IsTsys *bool `json:"isTsys,omitempty"`
	IsDisputable *string `json:"isDisputable,omitempty"`
	OriginalAmount *ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner `json:"originalAmount,omitempty"`
	RunningBalance map[string]interface{} `json:"runningBalance,omitempty"`
	AssociatedCardNumber *string `json:"associatedCardNumber,omitempty"`
	PurchaseCountryCode map[string]interface{} `json:"purchaseCountryCode,omitempty"`
	OutOfCountryIndicator map[string]interface{} `json:"outOfCountryIndicator,omitempty"`
	ReferenceNumber map[string]interface{} `json:"referenceNumber,omitempty"`
	ReasonCode map[string]interface{} `json:"reasonCode,omitempty"`
	Status *string `json:"status,omitempty"`
	RecurringPaymentIndicator *string `json:"recurringPaymentIndicator,omitempty"`
	StatementIndicator map[string]interface{} `json:"statementIndicator,omitempty"`
	FromAccount map[string]interface{} `json:"fromAccount,omitempty"`
	ToAccount map[string]interface{} `json:"toAccount,omitempty"`
	PurchaseType map[string]interface{} `json:"purchaseType,omitempty"`
	RewardsCategory map[string]interface{} `json:"rewardsCategory,omitempty"`
	RewardCard map[string]interface{} `json:"rewardCard,omitempty"`
	Category map[string]interface{} `json:"category,omitempty"`
	UserInputTag map[string]interface{} `json:"userInputTag,omitempty"`
	Cheque map[string]interface{} `json:"cheque,omitempty"`
	Merchant *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInnerMerchant `json:"merchant,omitempty"`
	Enriched *bool `json:"enriched,omitempty"`
	AcquirerReferenceNumber map[string]interface{} `json:"acquirerReferenceNumber,omitempty"`
	TransactionId *string `json:"transactionId,omitempty"`
	TransactionKey *string `json:"transactionKey,omitempty"`
	TransactionDate *string `json:"transactionDate,omitempty"`
	TransactionCode map[string]interface{} `json:"transactionCode,omitempty"`
	TransactionAmount *ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner `json:"transactionAmount,omitempty"`
	TransactionType *string `json:"transactionType,omitempty"`
	TransactionCategory map[string]interface{} `json:"transactionCategory,omitempty"`
	Subdescription map[string]interface{} `json:"subdescription,omitempty"`
}

// NewApiCreditCreditIdTransactionsGet200ResponseDataPendingInner instantiates a new ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCreditCreditIdTransactionsGet200ResponseDataPendingInner() *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner {
	this := ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner{}
	return &this
}

// NewApiCreditCreditIdTransactionsGet200ResponseDataPendingInnerWithDefaults instantiates a new ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCreditCreditIdTransactionsGet200ResponseDataPendingInnerWithDefaults() *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner {
	this := ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetKey(v string) {
	o.Key = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetId(v string) {
	o.Id = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetDescription(v string) {
	o.Description = &v
}

// GetDescriptionLines returns the DescriptionLines field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetDescriptionLines() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.DescriptionLines
}

// GetDescriptionLinesOk returns a tuple with the DescriptionLines field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetDescriptionLinesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.DescriptionLines) {
		return map[string]interface{}{}, false
	}
	return o.DescriptionLines, true
}

// HasDescriptionLines returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasDescriptionLines() bool {
	if o != nil && !IsNil(o.DescriptionLines) {
		return true
	}

	return false
}

// SetDescriptionLines gets a reference to the given map[string]interface{} and assigns it to the DescriptionLines field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetDescriptionLines(v map[string]interface{}) {
	o.DescriptionLines = v
}

// GetSubDescription returns the SubDescription field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetSubDescription() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.SubDescription
}

// GetSubDescriptionOk returns a tuple with the SubDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetSubDescriptionOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.SubDescription) {
		return map[string]interface{}{}, false
	}
	return o.SubDescription, true
}

// HasSubDescription returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasSubDescription() bool {
	if o != nil && !IsNil(o.SubDescription) {
		return true
	}

	return false
}

// SetSubDescription gets a reference to the given map[string]interface{} and assigns it to the SubDescription field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetSubDescription(v map[string]interface{}) {
	o.SubDescription = v
}

// GetCleanDescription returns the CleanDescription field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetCleanDescription() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.CleanDescription
}

// GetCleanDescriptionOk returns a tuple with the CleanDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetCleanDescriptionOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CleanDescription) {
		return map[string]interface{}{}, false
	}
	return o.CleanDescription, true
}

// HasCleanDescription returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasCleanDescription() bool {
	if o != nil && !IsNil(o.CleanDescription) {
		return true
	}

	return false
}

// SetCleanDescription gets a reference to the given map[string]interface{} and assigns it to the CleanDescription field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetCleanDescription(v map[string]interface{}) {
	o.CleanDescription = v
}

// GetMnemonicCode returns the MnemonicCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetMnemonicCode() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.MnemonicCode
}

// GetMnemonicCodeOk returns a tuple with the MnemonicCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetMnemonicCodeOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.MnemonicCode) {
		return map[string]interface{}{}, false
	}
	return o.MnemonicCode, true
}

// HasMnemonicCode returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasMnemonicCode() bool {
	if o != nil && !IsNil(o.MnemonicCode) {
		return true
	}

	return false
}

// SetMnemonicCode gets a reference to the given map[string]interface{} and assigns it to the MnemonicCode field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetMnemonicCode(v map[string]interface{}) {
	o.MnemonicCode = v
}

// GetType returns the Type field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetType() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetTypeOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return map[string]interface{}{}, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given map[string]interface{} and assigns it to the Type field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetType(v map[string]interface{}) {
	o.Type = v
}

// GetTsysCode returns the TsysCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetTsysCode() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.TsysCode
}

// GetTsysCodeOk returns a tuple with the TsysCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetTsysCodeOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.TsysCode) {
		return map[string]interface{}{}, false
	}
	return o.TsysCode, true
}

// HasTsysCode returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasTsysCode() bool {
	if o != nil && !IsNil(o.TsysCode) {
		return true
	}

	return false
}

// SetTsysCode gets a reference to the given map[string]interface{} and assigns it to the TsysCode field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetTsysCode(v map[string]interface{}) {
	o.TsysCode = v
}

// GetIsTsys returns the IsTsys field value if set, zero value otherwise.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetIsTsys() bool {
	if o == nil || IsNil(o.IsTsys) {
		var ret bool
		return ret
	}
	return *o.IsTsys
}

// GetIsTsysOk returns a tuple with the IsTsys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetIsTsysOk() (*bool, bool) {
	if o == nil || IsNil(o.IsTsys) {
		return nil, false
	}
	return o.IsTsys, true
}

// HasIsTsys returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasIsTsys() bool {
	if o != nil && !IsNil(o.IsTsys) {
		return true
	}

	return false
}

// SetIsTsys gets a reference to the given bool and assigns it to the IsTsys field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetIsTsys(v bool) {
	o.IsTsys = &v
}

// GetIsDisputable returns the IsDisputable field value if set, zero value otherwise.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetIsDisputable() string {
	if o == nil || IsNil(o.IsDisputable) {
		var ret string
		return ret
	}
	return *o.IsDisputable
}

// GetIsDisputableOk returns a tuple with the IsDisputable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetIsDisputableOk() (*string, bool) {
	if o == nil || IsNil(o.IsDisputable) {
		return nil, false
	}
	return o.IsDisputable, true
}

// HasIsDisputable returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasIsDisputable() bool {
	if o != nil && !IsNil(o.IsDisputable) {
		return true
	}

	return false
}

// SetIsDisputable gets a reference to the given string and assigns it to the IsDisputable field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetIsDisputable(v string) {
	o.IsDisputable = &v
}

// GetOriginalAmount returns the OriginalAmount field value if set, zero value otherwise.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetOriginalAmount() ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner {
	if o == nil || IsNil(o.OriginalAmount) {
		var ret ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner
		return ret
	}
	return *o.OriginalAmount
}

// GetOriginalAmountOk returns a tuple with the OriginalAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetOriginalAmountOk() (*ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner, bool) {
	if o == nil || IsNil(o.OriginalAmount) {
		return nil, false
	}
	return o.OriginalAmount, true
}

// HasOriginalAmount returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasOriginalAmount() bool {
	if o != nil && !IsNil(o.OriginalAmount) {
		return true
	}

	return false
}

// SetOriginalAmount gets a reference to the given ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner and assigns it to the OriginalAmount field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetOriginalAmount(v ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner) {
	o.OriginalAmount = &v
}

// GetRunningBalance returns the RunningBalance field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetRunningBalance() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.RunningBalance
}

// GetRunningBalanceOk returns a tuple with the RunningBalance field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetRunningBalanceOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.RunningBalance) {
		return map[string]interface{}{}, false
	}
	return o.RunningBalance, true
}

// HasRunningBalance returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasRunningBalance() bool {
	if o != nil && !IsNil(o.RunningBalance) {
		return true
	}

	return false
}

// SetRunningBalance gets a reference to the given map[string]interface{} and assigns it to the RunningBalance field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetRunningBalance(v map[string]interface{}) {
	o.RunningBalance = v
}

// GetAssociatedCardNumber returns the AssociatedCardNumber field value if set, zero value otherwise.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetAssociatedCardNumber() string {
	if o == nil || IsNil(o.AssociatedCardNumber) {
		var ret string
		return ret
	}
	return *o.AssociatedCardNumber
}

// GetAssociatedCardNumberOk returns a tuple with the AssociatedCardNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetAssociatedCardNumberOk() (*string, bool) {
	if o == nil || IsNil(o.AssociatedCardNumber) {
		return nil, false
	}
	return o.AssociatedCardNumber, true
}

// HasAssociatedCardNumber returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasAssociatedCardNumber() bool {
	if o != nil && !IsNil(o.AssociatedCardNumber) {
		return true
	}

	return false
}

// SetAssociatedCardNumber gets a reference to the given string and assigns it to the AssociatedCardNumber field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetAssociatedCardNumber(v string) {
	o.AssociatedCardNumber = &v
}

// GetPurchaseCountryCode returns the PurchaseCountryCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetPurchaseCountryCode() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.PurchaseCountryCode
}

// GetPurchaseCountryCodeOk returns a tuple with the PurchaseCountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetPurchaseCountryCodeOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.PurchaseCountryCode) {
		return map[string]interface{}{}, false
	}
	return o.PurchaseCountryCode, true
}

// HasPurchaseCountryCode returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasPurchaseCountryCode() bool {
	if o != nil && !IsNil(o.PurchaseCountryCode) {
		return true
	}

	return false
}

// SetPurchaseCountryCode gets a reference to the given map[string]interface{} and assigns it to the PurchaseCountryCode field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetPurchaseCountryCode(v map[string]interface{}) {
	o.PurchaseCountryCode = v
}

// GetOutOfCountryIndicator returns the OutOfCountryIndicator field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetOutOfCountryIndicator() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.OutOfCountryIndicator
}

// GetOutOfCountryIndicatorOk returns a tuple with the OutOfCountryIndicator field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetOutOfCountryIndicatorOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.OutOfCountryIndicator) {
		return map[string]interface{}{}, false
	}
	return o.OutOfCountryIndicator, true
}

// HasOutOfCountryIndicator returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasOutOfCountryIndicator() bool {
	if o != nil && !IsNil(o.OutOfCountryIndicator) {
		return true
	}

	return false
}

// SetOutOfCountryIndicator gets a reference to the given map[string]interface{} and assigns it to the OutOfCountryIndicator field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetOutOfCountryIndicator(v map[string]interface{}) {
	o.OutOfCountryIndicator = v
}

// GetReferenceNumber returns the ReferenceNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetReferenceNumber() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.ReferenceNumber
}

// GetReferenceNumberOk returns a tuple with the ReferenceNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetReferenceNumberOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ReferenceNumber) {
		return map[string]interface{}{}, false
	}
	return o.ReferenceNumber, true
}

// HasReferenceNumber returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasReferenceNumber() bool {
	if o != nil && !IsNil(o.ReferenceNumber) {
		return true
	}

	return false
}

// SetReferenceNumber gets a reference to the given map[string]interface{} and assigns it to the ReferenceNumber field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetReferenceNumber(v map[string]interface{}) {
	o.ReferenceNumber = v
}

// GetReasonCode returns the ReasonCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetReasonCode() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.ReasonCode
}

// GetReasonCodeOk returns a tuple with the ReasonCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetReasonCodeOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ReasonCode) {
		return map[string]interface{}{}, false
	}
	return o.ReasonCode, true
}

// HasReasonCode returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasReasonCode() bool {
	if o != nil && !IsNil(o.ReasonCode) {
		return true
	}

	return false
}

// SetReasonCode gets a reference to the given map[string]interface{} and assigns it to the ReasonCode field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetReasonCode(v map[string]interface{}) {
	o.ReasonCode = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetStatus(v string) {
	o.Status = &v
}

// GetRecurringPaymentIndicator returns the RecurringPaymentIndicator field value if set, zero value otherwise.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetRecurringPaymentIndicator() string {
	if o == nil || IsNil(o.RecurringPaymentIndicator) {
		var ret string
		return ret
	}
	return *o.RecurringPaymentIndicator
}

// GetRecurringPaymentIndicatorOk returns a tuple with the RecurringPaymentIndicator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetRecurringPaymentIndicatorOk() (*string, bool) {
	if o == nil || IsNil(o.RecurringPaymentIndicator) {
		return nil, false
	}
	return o.RecurringPaymentIndicator, true
}

// HasRecurringPaymentIndicator returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasRecurringPaymentIndicator() bool {
	if o != nil && !IsNil(o.RecurringPaymentIndicator) {
		return true
	}

	return false
}

// SetRecurringPaymentIndicator gets a reference to the given string and assigns it to the RecurringPaymentIndicator field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetRecurringPaymentIndicator(v string) {
	o.RecurringPaymentIndicator = &v
}

// GetStatementIndicator returns the StatementIndicator field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetStatementIndicator() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.StatementIndicator
}

// GetStatementIndicatorOk returns a tuple with the StatementIndicator field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetStatementIndicatorOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.StatementIndicator) {
		return map[string]interface{}{}, false
	}
	return o.StatementIndicator, true
}

// HasStatementIndicator returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasStatementIndicator() bool {
	if o != nil && !IsNil(o.StatementIndicator) {
		return true
	}

	return false
}

// SetStatementIndicator gets a reference to the given map[string]interface{} and assigns it to the StatementIndicator field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetStatementIndicator(v map[string]interface{}) {
	o.StatementIndicator = v
}

// GetFromAccount returns the FromAccount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetFromAccount() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.FromAccount
}

// GetFromAccountOk returns a tuple with the FromAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetFromAccountOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.FromAccount) {
		return map[string]interface{}{}, false
	}
	return o.FromAccount, true
}

// HasFromAccount returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasFromAccount() bool {
	if o != nil && !IsNil(o.FromAccount) {
		return true
	}

	return false
}

// SetFromAccount gets a reference to the given map[string]interface{} and assigns it to the FromAccount field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetFromAccount(v map[string]interface{}) {
	o.FromAccount = v
}

// GetToAccount returns the ToAccount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetToAccount() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.ToAccount
}

// GetToAccountOk returns a tuple with the ToAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetToAccountOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ToAccount) {
		return map[string]interface{}{}, false
	}
	return o.ToAccount, true
}

// HasToAccount returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasToAccount() bool {
	if o != nil && !IsNil(o.ToAccount) {
		return true
	}

	return false
}

// SetToAccount gets a reference to the given map[string]interface{} and assigns it to the ToAccount field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetToAccount(v map[string]interface{}) {
	o.ToAccount = v
}

// GetPurchaseType returns the PurchaseType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetPurchaseType() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.PurchaseType
}

// GetPurchaseTypeOk returns a tuple with the PurchaseType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetPurchaseTypeOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.PurchaseType) {
		return map[string]interface{}{}, false
	}
	return o.PurchaseType, true
}

// HasPurchaseType returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasPurchaseType() bool {
	if o != nil && !IsNil(o.PurchaseType) {
		return true
	}

	return false
}

// SetPurchaseType gets a reference to the given map[string]interface{} and assigns it to the PurchaseType field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetPurchaseType(v map[string]interface{}) {
	o.PurchaseType = v
}

// GetRewardsCategory returns the RewardsCategory field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetRewardsCategory() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.RewardsCategory
}

// GetRewardsCategoryOk returns a tuple with the RewardsCategory field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetRewardsCategoryOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.RewardsCategory) {
		return map[string]interface{}{}, false
	}
	return o.RewardsCategory, true
}

// HasRewardsCategory returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasRewardsCategory() bool {
	if o != nil && !IsNil(o.RewardsCategory) {
		return true
	}

	return false
}

// SetRewardsCategory gets a reference to the given map[string]interface{} and assigns it to the RewardsCategory field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetRewardsCategory(v map[string]interface{}) {
	o.RewardsCategory = v
}

// GetRewardCard returns the RewardCard field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetRewardCard() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.RewardCard
}

// GetRewardCardOk returns a tuple with the RewardCard field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetRewardCardOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.RewardCard) {
		return map[string]interface{}{}, false
	}
	return o.RewardCard, true
}

// HasRewardCard returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasRewardCard() bool {
	if o != nil && !IsNil(o.RewardCard) {
		return true
	}

	return false
}

// SetRewardCard gets a reference to the given map[string]interface{} and assigns it to the RewardCard field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetRewardCard(v map[string]interface{}) {
	o.RewardCard = v
}

// GetCategory returns the Category field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetCategory() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetCategoryOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Category) {
		return map[string]interface{}{}, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given map[string]interface{} and assigns it to the Category field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetCategory(v map[string]interface{}) {
	o.Category = v
}

// GetUserInputTag returns the UserInputTag field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetUserInputTag() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.UserInputTag
}

// GetUserInputTagOk returns a tuple with the UserInputTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetUserInputTagOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.UserInputTag) {
		return map[string]interface{}{}, false
	}
	return o.UserInputTag, true
}

// HasUserInputTag returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasUserInputTag() bool {
	if o != nil && !IsNil(o.UserInputTag) {
		return true
	}

	return false
}

// SetUserInputTag gets a reference to the given map[string]interface{} and assigns it to the UserInputTag field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetUserInputTag(v map[string]interface{}) {
	o.UserInputTag = v
}

// GetCheque returns the Cheque field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetCheque() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Cheque
}

// GetChequeOk returns a tuple with the Cheque field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetChequeOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Cheque) {
		return map[string]interface{}{}, false
	}
	return o.Cheque, true
}

// HasCheque returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasCheque() bool {
	if o != nil && !IsNil(o.Cheque) {
		return true
	}

	return false
}

// SetCheque gets a reference to the given map[string]interface{} and assigns it to the Cheque field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetCheque(v map[string]interface{}) {
	o.Cheque = v
}

// GetMerchant returns the Merchant field value if set, zero value otherwise.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetMerchant() ApiCreditCreditIdTransactionsGet200ResponseDataPendingInnerMerchant {
	if o == nil || IsNil(o.Merchant) {
		var ret ApiCreditCreditIdTransactionsGet200ResponseDataPendingInnerMerchant
		return ret
	}
	return *o.Merchant
}

// GetMerchantOk returns a tuple with the Merchant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetMerchantOk() (*ApiCreditCreditIdTransactionsGet200ResponseDataPendingInnerMerchant, bool) {
	if o == nil || IsNil(o.Merchant) {
		return nil, false
	}
	return o.Merchant, true
}

// HasMerchant returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasMerchant() bool {
	if o != nil && !IsNil(o.Merchant) {
		return true
	}

	return false
}

// SetMerchant gets a reference to the given ApiCreditCreditIdTransactionsGet200ResponseDataPendingInnerMerchant and assigns it to the Merchant field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetMerchant(v ApiCreditCreditIdTransactionsGet200ResponseDataPendingInnerMerchant) {
	o.Merchant = &v
}

// GetEnriched returns the Enriched field value if set, zero value otherwise.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetEnriched() bool {
	if o == nil || IsNil(o.Enriched) {
		var ret bool
		return ret
	}
	return *o.Enriched
}

// GetEnrichedOk returns a tuple with the Enriched field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetEnrichedOk() (*bool, bool) {
	if o == nil || IsNil(o.Enriched) {
		return nil, false
	}
	return o.Enriched, true
}

// HasEnriched returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasEnriched() bool {
	if o != nil && !IsNil(o.Enriched) {
		return true
	}

	return false
}

// SetEnriched gets a reference to the given bool and assigns it to the Enriched field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetEnriched(v bool) {
	o.Enriched = &v
}

// GetAcquirerReferenceNumber returns the AcquirerReferenceNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetAcquirerReferenceNumber() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.AcquirerReferenceNumber
}

// GetAcquirerReferenceNumberOk returns a tuple with the AcquirerReferenceNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetAcquirerReferenceNumberOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.AcquirerReferenceNumber) {
		return map[string]interface{}{}, false
	}
	return o.AcquirerReferenceNumber, true
}

// HasAcquirerReferenceNumber returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasAcquirerReferenceNumber() bool {
	if o != nil && !IsNil(o.AcquirerReferenceNumber) {
		return true
	}

	return false
}

// SetAcquirerReferenceNumber gets a reference to the given map[string]interface{} and assigns it to the AcquirerReferenceNumber field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetAcquirerReferenceNumber(v map[string]interface{}) {
	o.AcquirerReferenceNumber = v
}

// GetTransactionId returns the TransactionId field value if set, zero value otherwise.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetTransactionId() string {
	if o == nil || IsNil(o.TransactionId) {
		var ret string
		return ret
	}
	return *o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetTransactionIdOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionId) {
		return nil, false
	}
	return o.TransactionId, true
}

// HasTransactionId returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasTransactionId() bool {
	if o != nil && !IsNil(o.TransactionId) {
		return true
	}

	return false
}

// SetTransactionId gets a reference to the given string and assigns it to the TransactionId field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetTransactionId(v string) {
	o.TransactionId = &v
}

// GetTransactionKey returns the TransactionKey field value if set, zero value otherwise.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetTransactionKey() string {
	if o == nil || IsNil(o.TransactionKey) {
		var ret string
		return ret
	}
	return *o.TransactionKey
}

// GetTransactionKeyOk returns a tuple with the TransactionKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetTransactionKeyOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionKey) {
		return nil, false
	}
	return o.TransactionKey, true
}

// HasTransactionKey returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasTransactionKey() bool {
	if o != nil && !IsNil(o.TransactionKey) {
		return true
	}

	return false
}

// SetTransactionKey gets a reference to the given string and assigns it to the TransactionKey field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetTransactionKey(v string) {
	o.TransactionKey = &v
}

// GetTransactionDate returns the TransactionDate field value if set, zero value otherwise.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetTransactionDate() string {
	if o == nil || IsNil(o.TransactionDate) {
		var ret string
		return ret
	}
	return *o.TransactionDate
}

// GetTransactionDateOk returns a tuple with the TransactionDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetTransactionDateOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionDate) {
		return nil, false
	}
	return o.TransactionDate, true
}

// HasTransactionDate returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasTransactionDate() bool {
	if o != nil && !IsNil(o.TransactionDate) {
		return true
	}

	return false
}

// SetTransactionDate gets a reference to the given string and assigns it to the TransactionDate field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetTransactionDate(v string) {
	o.TransactionDate = &v
}

// GetTransactionCode returns the TransactionCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetTransactionCode() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.TransactionCode
}

// GetTransactionCodeOk returns a tuple with the TransactionCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetTransactionCodeOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.TransactionCode) {
		return map[string]interface{}{}, false
	}
	return o.TransactionCode, true
}

// HasTransactionCode returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasTransactionCode() bool {
	if o != nil && !IsNil(o.TransactionCode) {
		return true
	}

	return false
}

// SetTransactionCode gets a reference to the given map[string]interface{} and assigns it to the TransactionCode field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetTransactionCode(v map[string]interface{}) {
	o.TransactionCode = v
}

// GetTransactionAmount returns the TransactionAmount field value if set, zero value otherwise.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetTransactionAmount() ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner {
	if o == nil || IsNil(o.TransactionAmount) {
		var ret ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner
		return ret
	}
	return *o.TransactionAmount
}

// GetTransactionAmountOk returns a tuple with the TransactionAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetTransactionAmountOk() (*ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner, bool) {
	if o == nil || IsNil(o.TransactionAmount) {
		return nil, false
	}
	return o.TransactionAmount, true
}

// HasTransactionAmount returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasTransactionAmount() bool {
	if o != nil && !IsNil(o.TransactionAmount) {
		return true
	}

	return false
}

// SetTransactionAmount gets a reference to the given ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner and assigns it to the TransactionAmount field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetTransactionAmount(v ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner) {
	o.TransactionAmount = &v
}

// GetTransactionType returns the TransactionType field value if set, zero value otherwise.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetTransactionType() string {
	if o == nil || IsNil(o.TransactionType) {
		var ret string
		return ret
	}
	return *o.TransactionType
}

// GetTransactionTypeOk returns a tuple with the TransactionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetTransactionTypeOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionType) {
		return nil, false
	}
	return o.TransactionType, true
}

// HasTransactionType returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasTransactionType() bool {
	if o != nil && !IsNil(o.TransactionType) {
		return true
	}

	return false
}

// SetTransactionType gets a reference to the given string and assigns it to the TransactionType field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetTransactionType(v string) {
	o.TransactionType = &v
}

// GetTransactionCategory returns the TransactionCategory field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetTransactionCategory() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.TransactionCategory
}

// GetTransactionCategoryOk returns a tuple with the TransactionCategory field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetTransactionCategoryOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.TransactionCategory) {
		return map[string]interface{}{}, false
	}
	return o.TransactionCategory, true
}

// HasTransactionCategory returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasTransactionCategory() bool {
	if o != nil && !IsNil(o.TransactionCategory) {
		return true
	}

	return false
}

// SetTransactionCategory gets a reference to the given map[string]interface{} and assigns it to the TransactionCategory field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetTransactionCategory(v map[string]interface{}) {
	o.TransactionCategory = v
}

// GetSubdescription returns the Subdescription field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetSubdescription() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Subdescription
}

// GetSubdescriptionOk returns a tuple with the Subdescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) GetSubdescriptionOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Subdescription) {
		return map[string]interface{}{}, false
	}
	return o.Subdescription, true
}

// HasSubdescription returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) HasSubdescription() bool {
	if o != nil && !IsNil(o.Subdescription) {
		return true
	}

	return false
}

// SetSubdescription gets a reference to the given map[string]interface{} and assigns it to the Subdescription field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) SetSubdescription(v map[string]interface{}) {
	o.Subdescription = v
}

func (o ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if o.DescriptionLines != nil {
		toSerialize["descriptionLines"] = o.DescriptionLines
	}
	if o.SubDescription != nil {
		toSerialize["subDescription"] = o.SubDescription
	}
	if o.CleanDescription != nil {
		toSerialize["cleanDescription"] = o.CleanDescription
	}
	if o.MnemonicCode != nil {
		toSerialize["mnemonicCode"] = o.MnemonicCode
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.TsysCode != nil {
		toSerialize["tsysCode"] = o.TsysCode
	}
	if !IsNil(o.IsTsys) {
		toSerialize["isTsys"] = o.IsTsys
	}
	if !IsNil(o.IsDisputable) {
		toSerialize["isDisputable"] = o.IsDisputable
	}
	if !IsNil(o.OriginalAmount) {
		toSerialize["originalAmount"] = o.OriginalAmount
	}
	if o.RunningBalance != nil {
		toSerialize["runningBalance"] = o.RunningBalance
	}
	if !IsNil(o.AssociatedCardNumber) {
		toSerialize["associatedCardNumber"] = o.AssociatedCardNumber
	}
	if o.PurchaseCountryCode != nil {
		toSerialize["purchaseCountryCode"] = o.PurchaseCountryCode
	}
	if o.OutOfCountryIndicator != nil {
		toSerialize["outOfCountryIndicator"] = o.OutOfCountryIndicator
	}
	if o.ReferenceNumber != nil {
		toSerialize["referenceNumber"] = o.ReferenceNumber
	}
	if o.ReasonCode != nil {
		toSerialize["reasonCode"] = o.ReasonCode
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.RecurringPaymentIndicator) {
		toSerialize["recurringPaymentIndicator"] = o.RecurringPaymentIndicator
	}
	if o.StatementIndicator != nil {
		toSerialize["statementIndicator"] = o.StatementIndicator
	}
	if o.FromAccount != nil {
		toSerialize["fromAccount"] = o.FromAccount
	}
	if o.ToAccount != nil {
		toSerialize["toAccount"] = o.ToAccount
	}
	if o.PurchaseType != nil {
		toSerialize["purchaseType"] = o.PurchaseType
	}
	if o.RewardsCategory != nil {
		toSerialize["rewardsCategory"] = o.RewardsCategory
	}
	if o.RewardCard != nil {
		toSerialize["rewardCard"] = o.RewardCard
	}
	if o.Category != nil {
		toSerialize["category"] = o.Category
	}
	if o.UserInputTag != nil {
		toSerialize["userInputTag"] = o.UserInputTag
	}
	if o.Cheque != nil {
		toSerialize["cheque"] = o.Cheque
	}
	if !IsNil(o.Merchant) {
		toSerialize["merchant"] = o.Merchant
	}
	if !IsNil(o.Enriched) {
		toSerialize["enriched"] = o.Enriched
	}
	if o.AcquirerReferenceNumber != nil {
		toSerialize["acquirerReferenceNumber"] = o.AcquirerReferenceNumber
	}
	if !IsNil(o.TransactionId) {
		toSerialize["transactionId"] = o.TransactionId
	}
	if !IsNil(o.TransactionKey) {
		toSerialize["transactionKey"] = o.TransactionKey
	}
	if !IsNil(o.TransactionDate) {
		toSerialize["transactionDate"] = o.TransactionDate
	}
	if o.TransactionCode != nil {
		toSerialize["transactionCode"] = o.TransactionCode
	}
	if !IsNil(o.TransactionAmount) {
		toSerialize["transactionAmount"] = o.TransactionAmount
	}
	if !IsNil(o.TransactionType) {
		toSerialize["transactionType"] = o.TransactionType
	}
	if o.TransactionCategory != nil {
		toSerialize["transactionCategory"] = o.TransactionCategory
	}
	if o.Subdescription != nil {
		toSerialize["subdescription"] = o.Subdescription
	}
	return toSerialize, nil
}

type NullableApiCreditCreditIdTransactionsGet200ResponseDataPendingInner struct {
	value *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner
	isSet bool
}

func (v NullableApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) Get() *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner {
	return v.value
}

func (v *NullableApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) Set(val *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCreditCreditIdTransactionsGet200ResponseDataPendingInner(val *ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) *NullableApiCreditCreditIdTransactionsGet200ResponseDataPendingInner {
	return &NullableApiCreditCreditIdTransactionsGet200ResponseDataPendingInner{value: val, isSet: true}
}

func (v NullableApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


