/*
secure.scotiabank.com.har Mitmproxy2Swagger

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails{}

// ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails struct for ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails
type ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails struct {
	Size *float32 `json:"size,omitempty"`
	Image *ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetailsImage `json:"image,omitempty"`
}

// NewApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails instantiates a new ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails() *ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails {
	this := ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails{}
	return &this
}

// NewApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetailsWithDefaults instantiates a new ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetailsWithDefaults() *ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails {
	this := ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails{}
	return &this
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails) GetSize() float32 {
	if o == nil || IsNil(o.Size) {
		var ret float32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails) GetSizeOk() (*float32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given float32 and assigns it to the Size field.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails) SetSize(v float32) {
	o.Size = &v
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails) GetImage() ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetailsImage {
	if o == nil || IsNil(o.Image) {
		var ret ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetailsImage
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails) GetImageOk() (*ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetailsImage, bool) {
	if o == nil || IsNil(o.Image) {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails) HasImage() bool {
	if o != nil && !IsNil(o.Image) {
		return true
	}

	return false
}

// SetImage gets a reference to the given ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetailsImage and assigns it to the Image field.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails) SetImage(v ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetailsImage) {
	o.Image = &v
}

func (o ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.Image) {
		toSerialize["image"] = o.Image
	}
	return toSerialize, nil
}

type NullableApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails struct {
	value *ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails
	isSet bool
}

func (v NullableApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails) Get() *ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails {
	return v.value
}

func (v *NullableApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails) Set(val *ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails(val *ApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails) *NullableApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails {
	return &NullableApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails{value: val, isSet: true}
}

func (v NullableApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCampaignsGet200ResponseDataItemsInnerContentImageFileDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


