/*
secure.scotiabank.com.har Mitmproxy2Swagger

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiCreditCreditIdTransactionsGet200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCreditCreditIdTransactionsGet200ResponseData{}

// ApiCreditCreditIdTransactionsGet200ResponseData struct for ApiCreditCreditIdTransactionsGet200ResponseData
type ApiCreditCreditIdTransactionsGet200ResponseData struct {
	Pending []ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner `json:"pending,omitempty"`
	Settled []ApiCreditCreditIdTransactionsGet200ResponseDataSettledInner `json:"settled,omitempty"`
	PendingTransactionBalance *ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner `json:"pendingTransactionBalance,omitempty"`
}

// NewApiCreditCreditIdTransactionsGet200ResponseData instantiates a new ApiCreditCreditIdTransactionsGet200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCreditCreditIdTransactionsGet200ResponseData() *ApiCreditCreditIdTransactionsGet200ResponseData {
	this := ApiCreditCreditIdTransactionsGet200ResponseData{}
	return &this
}

// NewApiCreditCreditIdTransactionsGet200ResponseDataWithDefaults instantiates a new ApiCreditCreditIdTransactionsGet200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCreditCreditIdTransactionsGet200ResponseDataWithDefaults() *ApiCreditCreditIdTransactionsGet200ResponseData {
	this := ApiCreditCreditIdTransactionsGet200ResponseData{}
	return &this
}

// GetPending returns the Pending field value if set, zero value otherwise.
func (o *ApiCreditCreditIdTransactionsGet200ResponseData) GetPending() []ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner {
	if o == nil || IsNil(o.Pending) {
		var ret []ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner
		return ret
	}
	return o.Pending
}

// GetPendingOk returns a tuple with the Pending field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseData) GetPendingOk() ([]ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner, bool) {
	if o == nil || IsNil(o.Pending) {
		return nil, false
	}
	return o.Pending, true
}

// HasPending returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseData) HasPending() bool {
	if o != nil && !IsNil(o.Pending) {
		return true
	}

	return false
}

// SetPending gets a reference to the given []ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner and assigns it to the Pending field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseData) SetPending(v []ApiCreditCreditIdTransactionsGet200ResponseDataPendingInner) {
	o.Pending = v
}

// GetSettled returns the Settled field value if set, zero value otherwise.
func (o *ApiCreditCreditIdTransactionsGet200ResponseData) GetSettled() []ApiCreditCreditIdTransactionsGet200ResponseDataSettledInner {
	if o == nil || IsNil(o.Settled) {
		var ret []ApiCreditCreditIdTransactionsGet200ResponseDataSettledInner
		return ret
	}
	return o.Settled
}

// GetSettledOk returns a tuple with the Settled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseData) GetSettledOk() ([]ApiCreditCreditIdTransactionsGet200ResponseDataSettledInner, bool) {
	if o == nil || IsNil(o.Settled) {
		return nil, false
	}
	return o.Settled, true
}

// HasSettled returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseData) HasSettled() bool {
	if o != nil && !IsNil(o.Settled) {
		return true
	}

	return false
}

// SetSettled gets a reference to the given []ApiCreditCreditIdTransactionsGet200ResponseDataSettledInner and assigns it to the Settled field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseData) SetSettled(v []ApiCreditCreditIdTransactionsGet200ResponseDataSettledInner) {
	o.Settled = v
}

// GetPendingTransactionBalance returns the PendingTransactionBalance field value if set, zero value otherwise.
func (o *ApiCreditCreditIdTransactionsGet200ResponseData) GetPendingTransactionBalance() ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner {
	if o == nil || IsNil(o.PendingTransactionBalance) {
		var ret ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner
		return ret
	}
	return *o.PendingTransactionBalance
}

// GetPendingTransactionBalanceOk returns a tuple with the PendingTransactionBalance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseData) GetPendingTransactionBalanceOk() (*ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner, bool) {
	if o == nil || IsNil(o.PendingTransactionBalance) {
		return nil, false
	}
	return o.PendingTransactionBalance, true
}

// HasPendingTransactionBalance returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseData) HasPendingTransactionBalance() bool {
	if o != nil && !IsNil(o.PendingTransactionBalance) {
		return true
	}

	return false
}

// SetPendingTransactionBalance gets a reference to the given ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner and assigns it to the PendingTransactionBalance field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseData) SetPendingTransactionBalance(v ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner) {
	o.PendingTransactionBalance = &v
}

func (o ApiCreditCreditIdTransactionsGet200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCreditCreditIdTransactionsGet200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Pending) {
		toSerialize["pending"] = o.Pending
	}
	if !IsNil(o.Settled) {
		toSerialize["settled"] = o.Settled
	}
	if !IsNil(o.PendingTransactionBalance) {
		toSerialize["pendingTransactionBalance"] = o.PendingTransactionBalance
	}
	return toSerialize, nil
}

type NullableApiCreditCreditIdTransactionsGet200ResponseData struct {
	value *ApiCreditCreditIdTransactionsGet200ResponseData
	isSet bool
}

func (v NullableApiCreditCreditIdTransactionsGet200ResponseData) Get() *ApiCreditCreditIdTransactionsGet200ResponseData {
	return v.value
}

func (v *NullableApiCreditCreditIdTransactionsGet200ResponseData) Set(val *ApiCreditCreditIdTransactionsGet200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCreditCreditIdTransactionsGet200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCreditCreditIdTransactionsGet200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCreditCreditIdTransactionsGet200ResponseData(val *ApiCreditCreditIdTransactionsGet200ResponseData) *NullableApiCreditCreditIdTransactionsGet200ResponseData {
	return &NullableApiCreditCreditIdTransactionsGet200ResponseData{value: val, isSet: true}
}

func (v NullableApiCreditCreditIdTransactionsGet200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCreditCreditIdTransactionsGet200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


