/*
secure.scotiabank.com.har Mitmproxy2Swagger

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiCampaignsGet200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCampaignsGet200ResponseData{}

// ApiCampaignsGet200ResponseData struct for ApiCampaignsGet200ResponseData
type ApiCampaignsGet200ResponseData struct {
	Total *float32 `json:"total,omitempty"`
	Limit *float32 `json:"limit,omitempty"`
	Items []ApiCampaignsGet200ResponseDataItemsInner `json:"items,omitempty"`
}

// NewApiCampaignsGet200ResponseData instantiates a new ApiCampaignsGet200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCampaignsGet200ResponseData() *ApiCampaignsGet200ResponseData {
	this := ApiCampaignsGet200ResponseData{}
	return &this
}

// NewApiCampaignsGet200ResponseDataWithDefaults instantiates a new ApiCampaignsGet200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCampaignsGet200ResponseDataWithDefaults() *ApiCampaignsGet200ResponseData {
	this := ApiCampaignsGet200ResponseData{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ApiCampaignsGet200ResponseData) GetTotal() float32 {
	if o == nil || IsNil(o.Total) {
		var ret float32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCampaignsGet200ResponseData) GetTotalOk() (*float32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ApiCampaignsGet200ResponseData) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given float32 and assigns it to the Total field.
func (o *ApiCampaignsGet200ResponseData) SetTotal(v float32) {
	o.Total = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *ApiCampaignsGet200ResponseData) GetLimit() float32 {
	if o == nil || IsNil(o.Limit) {
		var ret float32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCampaignsGet200ResponseData) GetLimitOk() (*float32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *ApiCampaignsGet200ResponseData) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given float32 and assigns it to the Limit field.
func (o *ApiCampaignsGet200ResponseData) SetLimit(v float32) {
	o.Limit = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *ApiCampaignsGet200ResponseData) GetItems() []ApiCampaignsGet200ResponseDataItemsInner {
	if o == nil || IsNil(o.Items) {
		var ret []ApiCampaignsGet200ResponseDataItemsInner
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCampaignsGet200ResponseData) GetItemsOk() ([]ApiCampaignsGet200ResponseDataItemsInner, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *ApiCampaignsGet200ResponseData) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []ApiCampaignsGet200ResponseDataItemsInner and assigns it to the Items field.
func (o *ApiCampaignsGet200ResponseData) SetItems(v []ApiCampaignsGet200ResponseDataItemsInner) {
	o.Items = v
}

func (o ApiCampaignsGet200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCampaignsGet200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableApiCampaignsGet200ResponseData struct {
	value *ApiCampaignsGet200ResponseData
	isSet bool
}

func (v NullableApiCampaignsGet200ResponseData) Get() *ApiCampaignsGet200ResponseData {
	return v.value
}

func (v *NullableApiCampaignsGet200ResponseData) Set(val *ApiCampaignsGet200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCampaignsGet200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCampaignsGet200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCampaignsGet200ResponseData(val *ApiCampaignsGet200ResponseData) *NullableApiCampaignsGet200ResponseData {
	return &NullableApiCampaignsGet200ResponseData{value: val, isSet: true}
}

func (v NullableApiCampaignsGet200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCampaignsGet200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


