/*
secure.scotiabank.com.har Mitmproxy2Swagger

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiCampaignsGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCampaignsGet200Response{}

// ApiCampaignsGet200Response struct for ApiCampaignsGet200Response
type ApiCampaignsGet200Response struct {
	Data *ApiCampaignsGet200ResponseData `json:"data,omitempty"`
}

// NewApiCampaignsGet200Response instantiates a new ApiCampaignsGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCampaignsGet200Response() *ApiCampaignsGet200Response {
	this := ApiCampaignsGet200Response{}
	return &this
}

// NewApiCampaignsGet200ResponseWithDefaults instantiates a new ApiCampaignsGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCampaignsGet200ResponseWithDefaults() *ApiCampaignsGet200Response {
	this := ApiCampaignsGet200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ApiCampaignsGet200Response) GetData() ApiCampaignsGet200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret ApiCampaignsGet200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCampaignsGet200Response) GetDataOk() (*ApiCampaignsGet200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ApiCampaignsGet200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ApiCampaignsGet200ResponseData and assigns it to the Data field.
func (o *ApiCampaignsGet200Response) SetData(v ApiCampaignsGet200ResponseData) {
	o.Data = &v
}

func (o ApiCampaignsGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCampaignsGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableApiCampaignsGet200Response struct {
	value *ApiCampaignsGet200Response
	isSet bool
}

func (v NullableApiCampaignsGet200Response) Get() *ApiCampaignsGet200Response {
	return v.value
}

func (v *NullableApiCampaignsGet200Response) Set(val *ApiCampaignsGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCampaignsGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCampaignsGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCampaignsGet200Response(val *ApiCampaignsGet200Response) *NullableApiCampaignsGet200Response {
	return &NullableApiCampaignsGet200Response{value: val, isSet: true}
}

func (v NullableApiCampaignsGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCampaignsGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


