/*
secure.scotiabank.com.har Mitmproxy2Swagger

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner{}

// ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner struct for ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner
type ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner struct {
	Key *string `json:"key,omitempty"`
	Id *string `json:"id,omitempty"`
	PostedDate NullableString `json:"postedDate,omitempty"`
	Description *string `json:"description,omitempty"`
	SubDescription NullableString `json:"subDescription,omitempty"`
	CleanDescription *string `json:"cleanDescription,omitempty"`
	TypeCode *string `json:"typeCode,omitempty"`
	MnemonicCode *string `json:"mnemonicCode,omitempty"`
	TsysCode NullableString `json:"tsysCode,omitempty"`
	IsTsys *bool `json:"isTsys,omitempty"`
	IsDisputable NullableBool `json:"isDisputable,omitempty"`
	OriginalAmount *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerOriginalAmount `json:"originalAmount,omitempty"`
	RunningBalance *ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner `json:"runningBalance,omitempty"`
	AssociatedCardNumber NullableString `json:"associatedCardNumber,omitempty"`
	PurchaseCountryCode NullableString `json:"purchaseCountryCode,omitempty"`
	OutOfCountryIndicator *bool `json:"outOfCountryIndicator,omitempty"`
	ReasonCode NullableString `json:"reasonCode,omitempty"`
	Status NullableString `json:"status,omitempty"`
	RecurringPaymentIndicator NullableString `json:"recurringPaymentIndicator,omitempty"`
	DirectionIndicator *string `json:"directionIndicator,omitempty"`
	StatementIndicator NullableString `json:"statementIndicator,omitempty"`
	FromAccount NullableString `json:"fromAccount,omitempty"`
	ToAccount NullableString `json:"toAccount,omitempty"`
	PurchaseType NullableString `json:"purchaseType,omitempty"`
	RewardsCategory NullableString `json:"rewardsCategory,omitempty"`
	RewardCard NullableString `json:"rewardCard,omitempty"`
	Category *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory `json:"category,omitempty"`
	UserInputTag NullableString `json:"userInputTag,omitempty"`
	Cheque NullableString `json:"cheque,omitempty"`
	Merchant *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerMerchant `json:"merchant,omitempty"`
	Enriched *bool `json:"enriched,omitempty"`
	AcquirerReferenceNumber NullableString `json:"acquirerReferenceNumber,omitempty"`
	TransactionId *string `json:"transactionId,omitempty"`
	Subdescription *string `json:"subdescription,omitempty"`
	TransactionDate *string `json:"transactionDate,omitempty"`
	Balance *ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner `json:"balance,omitempty"`
	TransactionKey *string `json:"transactionKey,omitempty"`
	TransactionAmount *ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner `json:"transactionAmount,omitempty"`
	TransactionCategory *string `json:"transactionCategory,omitempty"`
	TransactionCategoryCode *string `json:"transactionCategoryCode,omitempty"`
	TransactionType *string `json:"transactionType,omitempty"`
	TransactionTypeCode *string `json:"transactionTypeCode,omitempty"`
	DescriptionLine1 *string `json:"descriptionLine1,omitempty"`
	DescriptionLine2 NullableString `json:"descriptionLine2,omitempty"`
}

// NewApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner instantiates a new ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner() *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner {
	this := ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner{}
	return &this
}

// NewApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerWithDefaults instantiates a new ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerWithDefaults() *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner {
	this := ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetKey(v string) {
	o.Key = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetId(v string) {
	o.Id = &v
}

// GetPostedDate returns the PostedDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetPostedDate() string {
	if o == nil || IsNil(o.PostedDate.Get()) {
		var ret string
		return ret
	}
	return *o.PostedDate.Get()
}

// GetPostedDateOk returns a tuple with the PostedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetPostedDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PostedDate.Get(), o.PostedDate.IsSet()
}

// HasPostedDate returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasPostedDate() bool {
	if o != nil && o.PostedDate.IsSet() {
		return true
	}

	return false
}

// SetPostedDate gets a reference to the given NullableString and assigns it to the PostedDate field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetPostedDate(v string) {
	o.PostedDate.Set(&v)
}
// SetPostedDateNil sets the value for PostedDate to be an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetPostedDateNil() {
	o.PostedDate.Set(nil)
}

// UnsetPostedDate ensures that no value is present for PostedDate, not even an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) UnsetPostedDate() {
	o.PostedDate.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetDescription(v string) {
	o.Description = &v
}

// GetSubDescription returns the SubDescription field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetSubDescription() string {
	if o == nil || IsNil(o.SubDescription.Get()) {
		var ret string
		return ret
	}
	return *o.SubDescription.Get()
}

// GetSubDescriptionOk returns a tuple with the SubDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetSubDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubDescription.Get(), o.SubDescription.IsSet()
}

// HasSubDescription returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasSubDescription() bool {
	if o != nil && o.SubDescription.IsSet() {
		return true
	}

	return false
}

// SetSubDescription gets a reference to the given NullableString and assigns it to the SubDescription field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetSubDescription(v string) {
	o.SubDescription.Set(&v)
}
// SetSubDescriptionNil sets the value for SubDescription to be an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetSubDescriptionNil() {
	o.SubDescription.Set(nil)
}

// UnsetSubDescription ensures that no value is present for SubDescription, not even an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) UnsetSubDescription() {
	o.SubDescription.Unset()
}

// GetCleanDescription returns the CleanDescription field value if set, zero value otherwise.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetCleanDescription() string {
	if o == nil || IsNil(o.CleanDescription) {
		var ret string
		return ret
	}
	return *o.CleanDescription
}

// GetCleanDescriptionOk returns a tuple with the CleanDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetCleanDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.CleanDescription) {
		return nil, false
	}
	return o.CleanDescription, true
}

// HasCleanDescription returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasCleanDescription() bool {
	if o != nil && !IsNil(o.CleanDescription) {
		return true
	}

	return false
}

// SetCleanDescription gets a reference to the given string and assigns it to the CleanDescription field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetCleanDescription(v string) {
	o.CleanDescription = &v
}

// GetTypeCode returns the TypeCode field value if set, zero value otherwise.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetTypeCode() string {
	if o == nil || IsNil(o.TypeCode) {
		var ret string
		return ret
	}
	return *o.TypeCode
}

// GetTypeCodeOk returns a tuple with the TypeCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetTypeCodeOk() (*string, bool) {
	if o == nil || IsNil(o.TypeCode) {
		return nil, false
	}
	return o.TypeCode, true
}

// HasTypeCode returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasTypeCode() bool {
	if o != nil && !IsNil(o.TypeCode) {
		return true
	}

	return false
}

// SetTypeCode gets a reference to the given string and assigns it to the TypeCode field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetTypeCode(v string) {
	o.TypeCode = &v
}

// GetMnemonicCode returns the MnemonicCode field value if set, zero value otherwise.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetMnemonicCode() string {
	if o == nil || IsNil(o.MnemonicCode) {
		var ret string
		return ret
	}
	return *o.MnemonicCode
}

// GetMnemonicCodeOk returns a tuple with the MnemonicCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetMnemonicCodeOk() (*string, bool) {
	if o == nil || IsNil(o.MnemonicCode) {
		return nil, false
	}
	return o.MnemonicCode, true
}

// HasMnemonicCode returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasMnemonicCode() bool {
	if o != nil && !IsNil(o.MnemonicCode) {
		return true
	}

	return false
}

// SetMnemonicCode gets a reference to the given string and assigns it to the MnemonicCode field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetMnemonicCode(v string) {
	o.MnemonicCode = &v
}

// GetTsysCode returns the TsysCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetTsysCode() string {
	if o == nil || IsNil(o.TsysCode.Get()) {
		var ret string
		return ret
	}
	return *o.TsysCode.Get()
}

// GetTsysCodeOk returns a tuple with the TsysCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetTsysCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TsysCode.Get(), o.TsysCode.IsSet()
}

// HasTsysCode returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasTsysCode() bool {
	if o != nil && o.TsysCode.IsSet() {
		return true
	}

	return false
}

// SetTsysCode gets a reference to the given NullableString and assigns it to the TsysCode field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetTsysCode(v string) {
	o.TsysCode.Set(&v)
}
// SetTsysCodeNil sets the value for TsysCode to be an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetTsysCodeNil() {
	o.TsysCode.Set(nil)
}

// UnsetTsysCode ensures that no value is present for TsysCode, not even an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) UnsetTsysCode() {
	o.TsysCode.Unset()
}

// GetIsTsys returns the IsTsys field value if set, zero value otherwise.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetIsTsys() bool {
	if o == nil || IsNil(o.IsTsys) {
		var ret bool
		return ret
	}
	return *o.IsTsys
}

// GetIsTsysOk returns a tuple with the IsTsys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetIsTsysOk() (*bool, bool) {
	if o == nil || IsNil(o.IsTsys) {
		return nil, false
	}
	return o.IsTsys, true
}

// HasIsTsys returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasIsTsys() bool {
	if o != nil && !IsNil(o.IsTsys) {
		return true
	}

	return false
}

// SetIsTsys gets a reference to the given bool and assigns it to the IsTsys field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetIsTsys(v bool) {
	o.IsTsys = &v
}

// GetIsDisputable returns the IsDisputable field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetIsDisputable() bool {
	if o == nil || IsNil(o.IsDisputable.Get()) {
		var ret bool
		return ret
	}
	return *o.IsDisputable.Get()
}

// GetIsDisputableOk returns a tuple with the IsDisputable field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetIsDisputableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsDisputable.Get(), o.IsDisputable.IsSet()
}

// HasIsDisputable returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasIsDisputable() bool {
	if o != nil && o.IsDisputable.IsSet() {
		return true
	}

	return false
}

// SetIsDisputable gets a reference to the given NullableBool and assigns it to the IsDisputable field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetIsDisputable(v bool) {
	o.IsDisputable.Set(&v)
}
// SetIsDisputableNil sets the value for IsDisputable to be an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetIsDisputableNil() {
	o.IsDisputable.Set(nil)
}

// UnsetIsDisputable ensures that no value is present for IsDisputable, not even an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) UnsetIsDisputable() {
	o.IsDisputable.Unset()
}

// GetOriginalAmount returns the OriginalAmount field value if set, zero value otherwise.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetOriginalAmount() ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerOriginalAmount {
	if o == nil || IsNil(o.OriginalAmount) {
		var ret ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerOriginalAmount
		return ret
	}
	return *o.OriginalAmount
}

// GetOriginalAmountOk returns a tuple with the OriginalAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetOriginalAmountOk() (*ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerOriginalAmount, bool) {
	if o == nil || IsNil(o.OriginalAmount) {
		return nil, false
	}
	return o.OriginalAmount, true
}

// HasOriginalAmount returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasOriginalAmount() bool {
	if o != nil && !IsNil(o.OriginalAmount) {
		return true
	}

	return false
}

// SetOriginalAmount gets a reference to the given ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerOriginalAmount and assigns it to the OriginalAmount field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetOriginalAmount(v ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerOriginalAmount) {
	o.OriginalAmount = &v
}

// GetRunningBalance returns the RunningBalance field value if set, zero value otherwise.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetRunningBalance() ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner {
	if o == nil || IsNil(o.RunningBalance) {
		var ret ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner
		return ret
	}
	return *o.RunningBalance
}

// GetRunningBalanceOk returns a tuple with the RunningBalance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetRunningBalanceOk() (*ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner, bool) {
	if o == nil || IsNil(o.RunningBalance) {
		return nil, false
	}
	return o.RunningBalance, true
}

// HasRunningBalance returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasRunningBalance() bool {
	if o != nil && !IsNil(o.RunningBalance) {
		return true
	}

	return false
}

// SetRunningBalance gets a reference to the given ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner and assigns it to the RunningBalance field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetRunningBalance(v ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner) {
	o.RunningBalance = &v
}

// GetAssociatedCardNumber returns the AssociatedCardNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetAssociatedCardNumber() string {
	if o == nil || IsNil(o.AssociatedCardNumber.Get()) {
		var ret string
		return ret
	}
	return *o.AssociatedCardNumber.Get()
}

// GetAssociatedCardNumberOk returns a tuple with the AssociatedCardNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetAssociatedCardNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AssociatedCardNumber.Get(), o.AssociatedCardNumber.IsSet()
}

// HasAssociatedCardNumber returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasAssociatedCardNumber() bool {
	if o != nil && o.AssociatedCardNumber.IsSet() {
		return true
	}

	return false
}

// SetAssociatedCardNumber gets a reference to the given NullableString and assigns it to the AssociatedCardNumber field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetAssociatedCardNumber(v string) {
	o.AssociatedCardNumber.Set(&v)
}
// SetAssociatedCardNumberNil sets the value for AssociatedCardNumber to be an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetAssociatedCardNumberNil() {
	o.AssociatedCardNumber.Set(nil)
}

// UnsetAssociatedCardNumber ensures that no value is present for AssociatedCardNumber, not even an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) UnsetAssociatedCardNumber() {
	o.AssociatedCardNumber.Unset()
}

// GetPurchaseCountryCode returns the PurchaseCountryCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetPurchaseCountryCode() string {
	if o == nil || IsNil(o.PurchaseCountryCode.Get()) {
		var ret string
		return ret
	}
	return *o.PurchaseCountryCode.Get()
}

// GetPurchaseCountryCodeOk returns a tuple with the PurchaseCountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetPurchaseCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PurchaseCountryCode.Get(), o.PurchaseCountryCode.IsSet()
}

// HasPurchaseCountryCode returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasPurchaseCountryCode() bool {
	if o != nil && o.PurchaseCountryCode.IsSet() {
		return true
	}

	return false
}

// SetPurchaseCountryCode gets a reference to the given NullableString and assigns it to the PurchaseCountryCode field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetPurchaseCountryCode(v string) {
	o.PurchaseCountryCode.Set(&v)
}
// SetPurchaseCountryCodeNil sets the value for PurchaseCountryCode to be an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetPurchaseCountryCodeNil() {
	o.PurchaseCountryCode.Set(nil)
}

// UnsetPurchaseCountryCode ensures that no value is present for PurchaseCountryCode, not even an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) UnsetPurchaseCountryCode() {
	o.PurchaseCountryCode.Unset()
}

// GetOutOfCountryIndicator returns the OutOfCountryIndicator field value if set, zero value otherwise.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetOutOfCountryIndicator() bool {
	if o == nil || IsNil(o.OutOfCountryIndicator) {
		var ret bool
		return ret
	}
	return *o.OutOfCountryIndicator
}

// GetOutOfCountryIndicatorOk returns a tuple with the OutOfCountryIndicator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetOutOfCountryIndicatorOk() (*bool, bool) {
	if o == nil || IsNil(o.OutOfCountryIndicator) {
		return nil, false
	}
	return o.OutOfCountryIndicator, true
}

// HasOutOfCountryIndicator returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasOutOfCountryIndicator() bool {
	if o != nil && !IsNil(o.OutOfCountryIndicator) {
		return true
	}

	return false
}

// SetOutOfCountryIndicator gets a reference to the given bool and assigns it to the OutOfCountryIndicator field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetOutOfCountryIndicator(v bool) {
	o.OutOfCountryIndicator = &v
}

// GetReasonCode returns the ReasonCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetReasonCode() string {
	if o == nil || IsNil(o.ReasonCode.Get()) {
		var ret string
		return ret
	}
	return *o.ReasonCode.Get()
}

// GetReasonCodeOk returns a tuple with the ReasonCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetReasonCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReasonCode.Get(), o.ReasonCode.IsSet()
}

// HasReasonCode returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasReasonCode() bool {
	if o != nil && o.ReasonCode.IsSet() {
		return true
	}

	return false
}

// SetReasonCode gets a reference to the given NullableString and assigns it to the ReasonCode field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetReasonCode(v string) {
	o.ReasonCode.Set(&v)
}
// SetReasonCodeNil sets the value for ReasonCode to be an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetReasonCodeNil() {
	o.ReasonCode.Set(nil)
}

// UnsetReasonCode ensures that no value is present for ReasonCode, not even an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) UnsetReasonCode() {
	o.ReasonCode.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetStatus() string {
	if o == nil || IsNil(o.Status.Get()) {
		var ret string
		return ret
	}
	return *o.Status.Get()
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Status.Get(), o.Status.IsSet()
}

// HasStatus returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasStatus() bool {
	if o != nil && o.Status.IsSet() {
		return true
	}

	return false
}

// SetStatus gets a reference to the given NullableString and assigns it to the Status field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetStatus(v string) {
	o.Status.Set(&v)
}
// SetStatusNil sets the value for Status to be an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetStatusNil() {
	o.Status.Set(nil)
}

// UnsetStatus ensures that no value is present for Status, not even an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) UnsetStatus() {
	o.Status.Unset()
}

// GetRecurringPaymentIndicator returns the RecurringPaymentIndicator field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetRecurringPaymentIndicator() string {
	if o == nil || IsNil(o.RecurringPaymentIndicator.Get()) {
		var ret string
		return ret
	}
	return *o.RecurringPaymentIndicator.Get()
}

// GetRecurringPaymentIndicatorOk returns a tuple with the RecurringPaymentIndicator field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetRecurringPaymentIndicatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RecurringPaymentIndicator.Get(), o.RecurringPaymentIndicator.IsSet()
}

// HasRecurringPaymentIndicator returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasRecurringPaymentIndicator() bool {
	if o != nil && o.RecurringPaymentIndicator.IsSet() {
		return true
	}

	return false
}

// SetRecurringPaymentIndicator gets a reference to the given NullableString and assigns it to the RecurringPaymentIndicator field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetRecurringPaymentIndicator(v string) {
	o.RecurringPaymentIndicator.Set(&v)
}
// SetRecurringPaymentIndicatorNil sets the value for RecurringPaymentIndicator to be an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetRecurringPaymentIndicatorNil() {
	o.RecurringPaymentIndicator.Set(nil)
}

// UnsetRecurringPaymentIndicator ensures that no value is present for RecurringPaymentIndicator, not even an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) UnsetRecurringPaymentIndicator() {
	o.RecurringPaymentIndicator.Unset()
}

// GetDirectionIndicator returns the DirectionIndicator field value if set, zero value otherwise.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetDirectionIndicator() string {
	if o == nil || IsNil(o.DirectionIndicator) {
		var ret string
		return ret
	}
	return *o.DirectionIndicator
}

// GetDirectionIndicatorOk returns a tuple with the DirectionIndicator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetDirectionIndicatorOk() (*string, bool) {
	if o == nil || IsNil(o.DirectionIndicator) {
		return nil, false
	}
	return o.DirectionIndicator, true
}

// HasDirectionIndicator returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasDirectionIndicator() bool {
	if o != nil && !IsNil(o.DirectionIndicator) {
		return true
	}

	return false
}

// SetDirectionIndicator gets a reference to the given string and assigns it to the DirectionIndicator field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetDirectionIndicator(v string) {
	o.DirectionIndicator = &v
}

// GetStatementIndicator returns the StatementIndicator field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetStatementIndicator() string {
	if o == nil || IsNil(o.StatementIndicator.Get()) {
		var ret string
		return ret
	}
	return *o.StatementIndicator.Get()
}

// GetStatementIndicatorOk returns a tuple with the StatementIndicator field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetStatementIndicatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StatementIndicator.Get(), o.StatementIndicator.IsSet()
}

// HasStatementIndicator returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasStatementIndicator() bool {
	if o != nil && o.StatementIndicator.IsSet() {
		return true
	}

	return false
}

// SetStatementIndicator gets a reference to the given NullableString and assigns it to the StatementIndicator field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetStatementIndicator(v string) {
	o.StatementIndicator.Set(&v)
}
// SetStatementIndicatorNil sets the value for StatementIndicator to be an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetStatementIndicatorNil() {
	o.StatementIndicator.Set(nil)
}

// UnsetStatementIndicator ensures that no value is present for StatementIndicator, not even an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) UnsetStatementIndicator() {
	o.StatementIndicator.Unset()
}

// GetFromAccount returns the FromAccount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetFromAccount() string {
	if o == nil || IsNil(o.FromAccount.Get()) {
		var ret string
		return ret
	}
	return *o.FromAccount.Get()
}

// GetFromAccountOk returns a tuple with the FromAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetFromAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FromAccount.Get(), o.FromAccount.IsSet()
}

// HasFromAccount returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasFromAccount() bool {
	if o != nil && o.FromAccount.IsSet() {
		return true
	}

	return false
}

// SetFromAccount gets a reference to the given NullableString and assigns it to the FromAccount field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetFromAccount(v string) {
	o.FromAccount.Set(&v)
}
// SetFromAccountNil sets the value for FromAccount to be an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetFromAccountNil() {
	o.FromAccount.Set(nil)
}

// UnsetFromAccount ensures that no value is present for FromAccount, not even an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) UnsetFromAccount() {
	o.FromAccount.Unset()
}

// GetToAccount returns the ToAccount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetToAccount() string {
	if o == nil || IsNil(o.ToAccount.Get()) {
		var ret string
		return ret
	}
	return *o.ToAccount.Get()
}

// GetToAccountOk returns a tuple with the ToAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetToAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ToAccount.Get(), o.ToAccount.IsSet()
}

// HasToAccount returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasToAccount() bool {
	if o != nil && o.ToAccount.IsSet() {
		return true
	}

	return false
}

// SetToAccount gets a reference to the given NullableString and assigns it to the ToAccount field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetToAccount(v string) {
	o.ToAccount.Set(&v)
}
// SetToAccountNil sets the value for ToAccount to be an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetToAccountNil() {
	o.ToAccount.Set(nil)
}

// UnsetToAccount ensures that no value is present for ToAccount, not even an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) UnsetToAccount() {
	o.ToAccount.Unset()
}

// GetPurchaseType returns the PurchaseType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetPurchaseType() string {
	if o == nil || IsNil(o.PurchaseType.Get()) {
		var ret string
		return ret
	}
	return *o.PurchaseType.Get()
}

// GetPurchaseTypeOk returns a tuple with the PurchaseType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetPurchaseTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PurchaseType.Get(), o.PurchaseType.IsSet()
}

// HasPurchaseType returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasPurchaseType() bool {
	if o != nil && o.PurchaseType.IsSet() {
		return true
	}

	return false
}

// SetPurchaseType gets a reference to the given NullableString and assigns it to the PurchaseType field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetPurchaseType(v string) {
	o.PurchaseType.Set(&v)
}
// SetPurchaseTypeNil sets the value for PurchaseType to be an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetPurchaseTypeNil() {
	o.PurchaseType.Set(nil)
}

// UnsetPurchaseType ensures that no value is present for PurchaseType, not even an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) UnsetPurchaseType() {
	o.PurchaseType.Unset()
}

// GetRewardsCategory returns the RewardsCategory field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetRewardsCategory() string {
	if o == nil || IsNil(o.RewardsCategory.Get()) {
		var ret string
		return ret
	}
	return *o.RewardsCategory.Get()
}

// GetRewardsCategoryOk returns a tuple with the RewardsCategory field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetRewardsCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RewardsCategory.Get(), o.RewardsCategory.IsSet()
}

// HasRewardsCategory returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasRewardsCategory() bool {
	if o != nil && o.RewardsCategory.IsSet() {
		return true
	}

	return false
}

// SetRewardsCategory gets a reference to the given NullableString and assigns it to the RewardsCategory field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetRewardsCategory(v string) {
	o.RewardsCategory.Set(&v)
}
// SetRewardsCategoryNil sets the value for RewardsCategory to be an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetRewardsCategoryNil() {
	o.RewardsCategory.Set(nil)
}

// UnsetRewardsCategory ensures that no value is present for RewardsCategory, not even an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) UnsetRewardsCategory() {
	o.RewardsCategory.Unset()
}

// GetRewardCard returns the RewardCard field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetRewardCard() string {
	if o == nil || IsNil(o.RewardCard.Get()) {
		var ret string
		return ret
	}
	return *o.RewardCard.Get()
}

// GetRewardCardOk returns a tuple with the RewardCard field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetRewardCardOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RewardCard.Get(), o.RewardCard.IsSet()
}

// HasRewardCard returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasRewardCard() bool {
	if o != nil && o.RewardCard.IsSet() {
		return true
	}

	return false
}

// SetRewardCard gets a reference to the given NullableString and assigns it to the RewardCard field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetRewardCard(v string) {
	o.RewardCard.Set(&v)
}
// SetRewardCardNil sets the value for RewardCard to be an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetRewardCardNil() {
	o.RewardCard.Set(nil)
}

// UnsetRewardCard ensures that no value is present for RewardCard, not even an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) UnsetRewardCard() {
	o.RewardCard.Unset()
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetCategory() ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory {
	if o == nil || IsNil(o.Category) {
		var ret ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetCategoryOk() (*ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory and assigns it to the Category field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetCategory(v ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory) {
	o.Category = &v
}

// GetUserInputTag returns the UserInputTag field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetUserInputTag() string {
	if o == nil || IsNil(o.UserInputTag.Get()) {
		var ret string
		return ret
	}
	return *o.UserInputTag.Get()
}

// GetUserInputTagOk returns a tuple with the UserInputTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetUserInputTagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserInputTag.Get(), o.UserInputTag.IsSet()
}

// HasUserInputTag returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasUserInputTag() bool {
	if o != nil && o.UserInputTag.IsSet() {
		return true
	}

	return false
}

// SetUserInputTag gets a reference to the given NullableString and assigns it to the UserInputTag field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetUserInputTag(v string) {
	o.UserInputTag.Set(&v)
}
// SetUserInputTagNil sets the value for UserInputTag to be an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetUserInputTagNil() {
	o.UserInputTag.Set(nil)
}

// UnsetUserInputTag ensures that no value is present for UserInputTag, not even an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) UnsetUserInputTag() {
	o.UserInputTag.Unset()
}

// GetCheque returns the Cheque field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetCheque() string {
	if o == nil || IsNil(o.Cheque.Get()) {
		var ret string
		return ret
	}
	return *o.Cheque.Get()
}

// GetChequeOk returns a tuple with the Cheque field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetChequeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Cheque.Get(), o.Cheque.IsSet()
}

// HasCheque returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasCheque() bool {
	if o != nil && o.Cheque.IsSet() {
		return true
	}

	return false
}

// SetCheque gets a reference to the given NullableString and assigns it to the Cheque field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetCheque(v string) {
	o.Cheque.Set(&v)
}
// SetChequeNil sets the value for Cheque to be an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetChequeNil() {
	o.Cheque.Set(nil)
}

// UnsetCheque ensures that no value is present for Cheque, not even an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) UnsetCheque() {
	o.Cheque.Unset()
}

// GetMerchant returns the Merchant field value if set, zero value otherwise.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetMerchant() ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerMerchant {
	if o == nil || IsNil(o.Merchant) {
		var ret ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerMerchant
		return ret
	}
	return *o.Merchant
}

// GetMerchantOk returns a tuple with the Merchant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetMerchantOk() (*ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerMerchant, bool) {
	if o == nil || IsNil(o.Merchant) {
		return nil, false
	}
	return o.Merchant, true
}

// HasMerchant returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasMerchant() bool {
	if o != nil && !IsNil(o.Merchant) {
		return true
	}

	return false
}

// SetMerchant gets a reference to the given ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerMerchant and assigns it to the Merchant field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetMerchant(v ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerMerchant) {
	o.Merchant = &v
}

// GetEnriched returns the Enriched field value if set, zero value otherwise.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetEnriched() bool {
	if o == nil || IsNil(o.Enriched) {
		var ret bool
		return ret
	}
	return *o.Enriched
}

// GetEnrichedOk returns a tuple with the Enriched field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetEnrichedOk() (*bool, bool) {
	if o == nil || IsNil(o.Enriched) {
		return nil, false
	}
	return o.Enriched, true
}

// HasEnriched returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasEnriched() bool {
	if o != nil && !IsNil(o.Enriched) {
		return true
	}

	return false
}

// SetEnriched gets a reference to the given bool and assigns it to the Enriched field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetEnriched(v bool) {
	o.Enriched = &v
}

// GetAcquirerReferenceNumber returns the AcquirerReferenceNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetAcquirerReferenceNumber() string {
	if o == nil || IsNil(o.AcquirerReferenceNumber.Get()) {
		var ret string
		return ret
	}
	return *o.AcquirerReferenceNumber.Get()
}

// GetAcquirerReferenceNumberOk returns a tuple with the AcquirerReferenceNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetAcquirerReferenceNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AcquirerReferenceNumber.Get(), o.AcquirerReferenceNumber.IsSet()
}

// HasAcquirerReferenceNumber returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasAcquirerReferenceNumber() bool {
	if o != nil && o.AcquirerReferenceNumber.IsSet() {
		return true
	}

	return false
}

// SetAcquirerReferenceNumber gets a reference to the given NullableString and assigns it to the AcquirerReferenceNumber field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetAcquirerReferenceNumber(v string) {
	o.AcquirerReferenceNumber.Set(&v)
}
// SetAcquirerReferenceNumberNil sets the value for AcquirerReferenceNumber to be an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetAcquirerReferenceNumberNil() {
	o.AcquirerReferenceNumber.Set(nil)
}

// UnsetAcquirerReferenceNumber ensures that no value is present for AcquirerReferenceNumber, not even an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) UnsetAcquirerReferenceNumber() {
	o.AcquirerReferenceNumber.Unset()
}

// GetTransactionId returns the TransactionId field value if set, zero value otherwise.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetTransactionId() string {
	if o == nil || IsNil(o.TransactionId) {
		var ret string
		return ret
	}
	return *o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetTransactionIdOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionId) {
		return nil, false
	}
	return o.TransactionId, true
}

// HasTransactionId returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasTransactionId() bool {
	if o != nil && !IsNil(o.TransactionId) {
		return true
	}

	return false
}

// SetTransactionId gets a reference to the given string and assigns it to the TransactionId field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetTransactionId(v string) {
	o.TransactionId = &v
}

// GetSubdescription returns the Subdescription field value if set, zero value otherwise.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetSubdescription() string {
	if o == nil || IsNil(o.Subdescription) {
		var ret string
		return ret
	}
	return *o.Subdescription
}

// GetSubdescriptionOk returns a tuple with the Subdescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetSubdescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Subdescription) {
		return nil, false
	}
	return o.Subdescription, true
}

// HasSubdescription returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasSubdescription() bool {
	if o != nil && !IsNil(o.Subdescription) {
		return true
	}

	return false
}

// SetSubdescription gets a reference to the given string and assigns it to the Subdescription field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetSubdescription(v string) {
	o.Subdescription = &v
}

// GetTransactionDate returns the TransactionDate field value if set, zero value otherwise.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetTransactionDate() string {
	if o == nil || IsNil(o.TransactionDate) {
		var ret string
		return ret
	}
	return *o.TransactionDate
}

// GetTransactionDateOk returns a tuple with the TransactionDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetTransactionDateOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionDate) {
		return nil, false
	}
	return o.TransactionDate, true
}

// HasTransactionDate returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasTransactionDate() bool {
	if o != nil && !IsNil(o.TransactionDate) {
		return true
	}

	return false
}

// SetTransactionDate gets a reference to the given string and assigns it to the TransactionDate field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetTransactionDate(v string) {
	o.TransactionDate = &v
}

// GetBalance returns the Balance field value if set, zero value otherwise.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetBalance() ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner {
	if o == nil || IsNil(o.Balance) {
		var ret ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner
		return ret
	}
	return *o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetBalanceOk() (*ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner, bool) {
	if o == nil || IsNil(o.Balance) {
		return nil, false
	}
	return o.Balance, true
}

// HasBalance returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasBalance() bool {
	if o != nil && !IsNil(o.Balance) {
		return true
	}

	return false
}

// SetBalance gets a reference to the given ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner and assigns it to the Balance field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetBalance(v ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner) {
	o.Balance = &v
}

// GetTransactionKey returns the TransactionKey field value if set, zero value otherwise.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetTransactionKey() string {
	if o == nil || IsNil(o.TransactionKey) {
		var ret string
		return ret
	}
	return *o.TransactionKey
}

// GetTransactionKeyOk returns a tuple with the TransactionKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetTransactionKeyOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionKey) {
		return nil, false
	}
	return o.TransactionKey, true
}

// HasTransactionKey returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasTransactionKey() bool {
	if o != nil && !IsNil(o.TransactionKey) {
		return true
	}

	return false
}

// SetTransactionKey gets a reference to the given string and assigns it to the TransactionKey field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetTransactionKey(v string) {
	o.TransactionKey = &v
}

// GetTransactionAmount returns the TransactionAmount field value if set, zero value otherwise.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetTransactionAmount() ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner {
	if o == nil || IsNil(o.TransactionAmount) {
		var ret ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner
		return ret
	}
	return *o.TransactionAmount
}

// GetTransactionAmountOk returns a tuple with the TransactionAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetTransactionAmountOk() (*ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner, bool) {
	if o == nil || IsNil(o.TransactionAmount) {
		return nil, false
	}
	return o.TransactionAmount, true
}

// HasTransactionAmount returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasTransactionAmount() bool {
	if o != nil && !IsNil(o.TransactionAmount) {
		return true
	}

	return false
}

// SetTransactionAmount gets a reference to the given ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner and assigns it to the TransactionAmount field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetTransactionAmount(v ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner) {
	o.TransactionAmount = &v
}

// GetTransactionCategory returns the TransactionCategory field value if set, zero value otherwise.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetTransactionCategory() string {
	if o == nil || IsNil(o.TransactionCategory) {
		var ret string
		return ret
	}
	return *o.TransactionCategory
}

// GetTransactionCategoryOk returns a tuple with the TransactionCategory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetTransactionCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionCategory) {
		return nil, false
	}
	return o.TransactionCategory, true
}

// HasTransactionCategory returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasTransactionCategory() bool {
	if o != nil && !IsNil(o.TransactionCategory) {
		return true
	}

	return false
}

// SetTransactionCategory gets a reference to the given string and assigns it to the TransactionCategory field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetTransactionCategory(v string) {
	o.TransactionCategory = &v
}

// GetTransactionCategoryCode returns the TransactionCategoryCode field value if set, zero value otherwise.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetTransactionCategoryCode() string {
	if o == nil || IsNil(o.TransactionCategoryCode) {
		var ret string
		return ret
	}
	return *o.TransactionCategoryCode
}

// GetTransactionCategoryCodeOk returns a tuple with the TransactionCategoryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetTransactionCategoryCodeOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionCategoryCode) {
		return nil, false
	}
	return o.TransactionCategoryCode, true
}

// HasTransactionCategoryCode returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasTransactionCategoryCode() bool {
	if o != nil && !IsNil(o.TransactionCategoryCode) {
		return true
	}

	return false
}

// SetTransactionCategoryCode gets a reference to the given string and assigns it to the TransactionCategoryCode field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetTransactionCategoryCode(v string) {
	o.TransactionCategoryCode = &v
}

// GetTransactionType returns the TransactionType field value if set, zero value otherwise.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetTransactionType() string {
	if o == nil || IsNil(o.TransactionType) {
		var ret string
		return ret
	}
	return *o.TransactionType
}

// GetTransactionTypeOk returns a tuple with the TransactionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetTransactionTypeOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionType) {
		return nil, false
	}
	return o.TransactionType, true
}

// HasTransactionType returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasTransactionType() bool {
	if o != nil && !IsNil(o.TransactionType) {
		return true
	}

	return false
}

// SetTransactionType gets a reference to the given string and assigns it to the TransactionType field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetTransactionType(v string) {
	o.TransactionType = &v
}

// GetTransactionTypeCode returns the TransactionTypeCode field value if set, zero value otherwise.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetTransactionTypeCode() string {
	if o == nil || IsNil(o.TransactionTypeCode) {
		var ret string
		return ret
	}
	return *o.TransactionTypeCode
}

// GetTransactionTypeCodeOk returns a tuple with the TransactionTypeCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetTransactionTypeCodeOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionTypeCode) {
		return nil, false
	}
	return o.TransactionTypeCode, true
}

// HasTransactionTypeCode returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasTransactionTypeCode() bool {
	if o != nil && !IsNil(o.TransactionTypeCode) {
		return true
	}

	return false
}

// SetTransactionTypeCode gets a reference to the given string and assigns it to the TransactionTypeCode field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetTransactionTypeCode(v string) {
	o.TransactionTypeCode = &v
}

// GetDescriptionLine1 returns the DescriptionLine1 field value if set, zero value otherwise.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetDescriptionLine1() string {
	if o == nil || IsNil(o.DescriptionLine1) {
		var ret string
		return ret
	}
	return *o.DescriptionLine1
}

// GetDescriptionLine1Ok returns a tuple with the DescriptionLine1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetDescriptionLine1Ok() (*string, bool) {
	if o == nil || IsNil(o.DescriptionLine1) {
		return nil, false
	}
	return o.DescriptionLine1, true
}

// HasDescriptionLine1 returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasDescriptionLine1() bool {
	if o != nil && !IsNil(o.DescriptionLine1) {
		return true
	}

	return false
}

// SetDescriptionLine1 gets a reference to the given string and assigns it to the DescriptionLine1 field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetDescriptionLine1(v string) {
	o.DescriptionLine1 = &v
}

// GetDescriptionLine2 returns the DescriptionLine2 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetDescriptionLine2() string {
	if o == nil || IsNil(o.DescriptionLine2.Get()) {
		var ret string
		return ret
	}
	return *o.DescriptionLine2.Get()
}

// GetDescriptionLine2Ok returns a tuple with the DescriptionLine2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) GetDescriptionLine2Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DescriptionLine2.Get(), o.DescriptionLine2.IsSet()
}

// HasDescriptionLine2 returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) HasDescriptionLine2() bool {
	if o != nil && o.DescriptionLine2.IsSet() {
		return true
	}

	return false
}

// SetDescriptionLine2 gets a reference to the given NullableString and assigns it to the DescriptionLine2 field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetDescriptionLine2(v string) {
	o.DescriptionLine2.Set(&v)
}
// SetDescriptionLine2Nil sets the value for DescriptionLine2 to be an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) SetDescriptionLine2Nil() {
	o.DescriptionLine2.Set(nil)
}

// UnsetDescriptionLine2 ensures that no value is present for DescriptionLine2, not even an explicit nil
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) UnsetDescriptionLine2() {
	o.DescriptionLine2.Unset()
}

func (o ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if o.PostedDate.IsSet() {
		toSerialize["postedDate"] = o.PostedDate.Get()
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if o.SubDescription.IsSet() {
		toSerialize["subDescription"] = o.SubDescription.Get()
	}
	if !IsNil(o.CleanDescription) {
		toSerialize["cleanDescription"] = o.CleanDescription
	}
	if !IsNil(o.TypeCode) {
		toSerialize["typeCode"] = o.TypeCode
	}
	if !IsNil(o.MnemonicCode) {
		toSerialize["mnemonicCode"] = o.MnemonicCode
	}
	if o.TsysCode.IsSet() {
		toSerialize["tsysCode"] = o.TsysCode.Get()
	}
	if !IsNil(o.IsTsys) {
		toSerialize["isTsys"] = o.IsTsys
	}
	if o.IsDisputable.IsSet() {
		toSerialize["isDisputable"] = o.IsDisputable.Get()
	}
	if !IsNil(o.OriginalAmount) {
		toSerialize["originalAmount"] = o.OriginalAmount
	}
	if !IsNil(o.RunningBalance) {
		toSerialize["runningBalance"] = o.RunningBalance
	}
	if o.AssociatedCardNumber.IsSet() {
		toSerialize["associatedCardNumber"] = o.AssociatedCardNumber.Get()
	}
	if o.PurchaseCountryCode.IsSet() {
		toSerialize["purchaseCountryCode"] = o.PurchaseCountryCode.Get()
	}
	if !IsNil(o.OutOfCountryIndicator) {
		toSerialize["outOfCountryIndicator"] = o.OutOfCountryIndicator
	}
	if o.ReasonCode.IsSet() {
		toSerialize["reasonCode"] = o.ReasonCode.Get()
	}
	if o.Status.IsSet() {
		toSerialize["status"] = o.Status.Get()
	}
	if o.RecurringPaymentIndicator.IsSet() {
		toSerialize["recurringPaymentIndicator"] = o.RecurringPaymentIndicator.Get()
	}
	if !IsNil(o.DirectionIndicator) {
		toSerialize["directionIndicator"] = o.DirectionIndicator
	}
	if o.StatementIndicator.IsSet() {
		toSerialize["statementIndicator"] = o.StatementIndicator.Get()
	}
	if o.FromAccount.IsSet() {
		toSerialize["fromAccount"] = o.FromAccount.Get()
	}
	if o.ToAccount.IsSet() {
		toSerialize["toAccount"] = o.ToAccount.Get()
	}
	if o.PurchaseType.IsSet() {
		toSerialize["purchaseType"] = o.PurchaseType.Get()
	}
	if o.RewardsCategory.IsSet() {
		toSerialize["rewardsCategory"] = o.RewardsCategory.Get()
	}
	if o.RewardCard.IsSet() {
		toSerialize["rewardCard"] = o.RewardCard.Get()
	}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if o.UserInputTag.IsSet() {
		toSerialize["userInputTag"] = o.UserInputTag.Get()
	}
	if o.Cheque.IsSet() {
		toSerialize["cheque"] = o.Cheque.Get()
	}
	if !IsNil(o.Merchant) {
		toSerialize["merchant"] = o.Merchant
	}
	if !IsNil(o.Enriched) {
		toSerialize["enriched"] = o.Enriched
	}
	if o.AcquirerReferenceNumber.IsSet() {
		toSerialize["acquirerReferenceNumber"] = o.AcquirerReferenceNumber.Get()
	}
	if !IsNil(o.TransactionId) {
		toSerialize["transactionId"] = o.TransactionId
	}
	if !IsNil(o.Subdescription) {
		toSerialize["subdescription"] = o.Subdescription
	}
	if !IsNil(o.TransactionDate) {
		toSerialize["transactionDate"] = o.TransactionDate
	}
	if !IsNil(o.Balance) {
		toSerialize["balance"] = o.Balance
	}
	if !IsNil(o.TransactionKey) {
		toSerialize["transactionKey"] = o.TransactionKey
	}
	if !IsNil(o.TransactionAmount) {
		toSerialize["transactionAmount"] = o.TransactionAmount
	}
	if !IsNil(o.TransactionCategory) {
		toSerialize["transactionCategory"] = o.TransactionCategory
	}
	if !IsNil(o.TransactionCategoryCode) {
		toSerialize["transactionCategoryCode"] = o.TransactionCategoryCode
	}
	if !IsNil(o.TransactionType) {
		toSerialize["transactionType"] = o.TransactionType
	}
	if !IsNil(o.TransactionTypeCode) {
		toSerialize["transactionTypeCode"] = o.TransactionTypeCode
	}
	if !IsNil(o.DescriptionLine1) {
		toSerialize["descriptionLine1"] = o.DescriptionLine1
	}
	if o.DescriptionLine2.IsSet() {
		toSerialize["descriptionLine2"] = o.DescriptionLine2.Get()
	}
	return toSerialize, nil
}

type NullableApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner struct {
	value *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner
	isSet bool
}

func (v NullableApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) Get() *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner {
	return v.value
}

func (v *NullableApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) Set(val *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner(val *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) *NullableApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner {
	return &NullableApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner{value: val, isSet: true}
}

func (v NullableApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


