/*
secure.scotiabank.com.har Mitmproxy2Swagger

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiMpsaAccountsAccountIdGet200ResponseDataInterest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiMpsaAccountsAccountIdGet200ResponseDataInterest{}

// ApiMpsaAccountsAccountIdGet200ResponseDataInterest struct for ApiMpsaAccountsAccountIdGet200ResponseDataInterest
type ApiMpsaAccountsAccountIdGet200ResponseDataInterest struct {
	Rate *float32 `json:"rate,omitempty"`
	Accrued *ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner `json:"accrued,omitempty"`
	AccrualPeriod *string `json:"accrualPeriod,omitempty"`
}

// NewApiMpsaAccountsAccountIdGet200ResponseDataInterest instantiates a new ApiMpsaAccountsAccountIdGet200ResponseDataInterest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiMpsaAccountsAccountIdGet200ResponseDataInterest() *ApiMpsaAccountsAccountIdGet200ResponseDataInterest {
	this := ApiMpsaAccountsAccountIdGet200ResponseDataInterest{}
	return &this
}

// NewApiMpsaAccountsAccountIdGet200ResponseDataInterestWithDefaults instantiates a new ApiMpsaAccountsAccountIdGet200ResponseDataInterest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiMpsaAccountsAccountIdGet200ResponseDataInterestWithDefaults() *ApiMpsaAccountsAccountIdGet200ResponseDataInterest {
	this := ApiMpsaAccountsAccountIdGet200ResponseDataInterest{}
	return &this
}

// GetRate returns the Rate field value if set, zero value otherwise.
func (o *ApiMpsaAccountsAccountIdGet200ResponseDataInterest) GetRate() float32 {
	if o == nil || IsNil(o.Rate) {
		var ret float32
		return ret
	}
	return *o.Rate
}

// GetRateOk returns a tuple with the Rate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMpsaAccountsAccountIdGet200ResponseDataInterest) GetRateOk() (*float32, bool) {
	if o == nil || IsNil(o.Rate) {
		return nil, false
	}
	return o.Rate, true
}

// HasRate returns a boolean if a field has been set.
func (o *ApiMpsaAccountsAccountIdGet200ResponseDataInterest) HasRate() bool {
	if o != nil && !IsNil(o.Rate) {
		return true
	}

	return false
}

// SetRate gets a reference to the given float32 and assigns it to the Rate field.
func (o *ApiMpsaAccountsAccountIdGet200ResponseDataInterest) SetRate(v float32) {
	o.Rate = &v
}

// GetAccrued returns the Accrued field value if set, zero value otherwise.
func (o *ApiMpsaAccountsAccountIdGet200ResponseDataInterest) GetAccrued() ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner {
	if o == nil || IsNil(o.Accrued) {
		var ret ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner
		return ret
	}
	return *o.Accrued
}

// GetAccruedOk returns a tuple with the Accrued field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMpsaAccountsAccountIdGet200ResponseDataInterest) GetAccruedOk() (*ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner, bool) {
	if o == nil || IsNil(o.Accrued) {
		return nil, false
	}
	return o.Accrued, true
}

// HasAccrued returns a boolean if a field has been set.
func (o *ApiMpsaAccountsAccountIdGet200ResponseDataInterest) HasAccrued() bool {
	if o != nil && !IsNil(o.Accrued) {
		return true
	}

	return false
}

// SetAccrued gets a reference to the given ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner and assigns it to the Accrued field.
func (o *ApiMpsaAccountsAccountIdGet200ResponseDataInterest) SetAccrued(v ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner) {
	o.Accrued = &v
}

// GetAccrualPeriod returns the AccrualPeriod field value if set, zero value otherwise.
func (o *ApiMpsaAccountsAccountIdGet200ResponseDataInterest) GetAccrualPeriod() string {
	if o == nil || IsNil(o.AccrualPeriod) {
		var ret string
		return ret
	}
	return *o.AccrualPeriod
}

// GetAccrualPeriodOk returns a tuple with the AccrualPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMpsaAccountsAccountIdGet200ResponseDataInterest) GetAccrualPeriodOk() (*string, bool) {
	if o == nil || IsNil(o.AccrualPeriod) {
		return nil, false
	}
	return o.AccrualPeriod, true
}

// HasAccrualPeriod returns a boolean if a field has been set.
func (o *ApiMpsaAccountsAccountIdGet200ResponseDataInterest) HasAccrualPeriod() bool {
	if o != nil && !IsNil(o.AccrualPeriod) {
		return true
	}

	return false
}

// SetAccrualPeriod gets a reference to the given string and assigns it to the AccrualPeriod field.
func (o *ApiMpsaAccountsAccountIdGet200ResponseDataInterest) SetAccrualPeriod(v string) {
	o.AccrualPeriod = &v
}

func (o ApiMpsaAccountsAccountIdGet200ResponseDataInterest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiMpsaAccountsAccountIdGet200ResponseDataInterest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Rate) {
		toSerialize["rate"] = o.Rate
	}
	if !IsNil(o.Accrued) {
		toSerialize["accrued"] = o.Accrued
	}
	if !IsNil(o.AccrualPeriod) {
		toSerialize["accrualPeriod"] = o.AccrualPeriod
	}
	return toSerialize, nil
}

type NullableApiMpsaAccountsAccountIdGet200ResponseDataInterest struct {
	value *ApiMpsaAccountsAccountIdGet200ResponseDataInterest
	isSet bool
}

func (v NullableApiMpsaAccountsAccountIdGet200ResponseDataInterest) Get() *ApiMpsaAccountsAccountIdGet200ResponseDataInterest {
	return v.value
}

func (v *NullableApiMpsaAccountsAccountIdGet200ResponseDataInterest) Set(val *ApiMpsaAccountsAccountIdGet200ResponseDataInterest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiMpsaAccountsAccountIdGet200ResponseDataInterest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiMpsaAccountsAccountIdGet200ResponseDataInterest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiMpsaAccountsAccountIdGet200ResponseDataInterest(val *ApiMpsaAccountsAccountIdGet200ResponseDataInterest) *NullableApiMpsaAccountsAccountIdGet200ResponseDataInterest {
	return &NullableApiMpsaAccountsAccountIdGet200ResponseDataInterest{value: val, isSet: true}
}

func (v NullableApiMpsaAccountsAccountIdGet200ResponseDataInterest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiMpsaAccountsAccountIdGet200ResponseDataInterest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


