/*
secure.scotiabank.com.har Mitmproxy2Swagger

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiCampaignsGet200ResponseDataItemsInnerContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCampaignsGet200ResponseDataItemsInnerContent{}

// ApiCampaignsGet200ResponseDataItemsInnerContent struct for ApiCampaignsGet200ResponseDataItemsInnerContent
type ApiCampaignsGet200ResponseDataItemsInnerContent struct {
	Title *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Image *ApiCampaignsGet200ResponseDataItemsInnerContentImage `json:"image,omitempty"`
	DetailLink *ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink `json:"detailLink,omitempty"`
}

// NewApiCampaignsGet200ResponseDataItemsInnerContent instantiates a new ApiCampaignsGet200ResponseDataItemsInnerContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCampaignsGet200ResponseDataItemsInnerContent() *ApiCampaignsGet200ResponseDataItemsInnerContent {
	this := ApiCampaignsGet200ResponseDataItemsInnerContent{}
	return &this
}

// NewApiCampaignsGet200ResponseDataItemsInnerContentWithDefaults instantiates a new ApiCampaignsGet200ResponseDataItemsInnerContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCampaignsGet200ResponseDataItemsInnerContentWithDefaults() *ApiCampaignsGet200ResponseDataItemsInnerContent {
	this := ApiCampaignsGet200ResponseDataItemsInnerContent{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContent) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContent) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContent) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContent) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContent) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContent) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContent) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContent) SetDescription(v string) {
	o.Description = &v
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContent) GetImage() ApiCampaignsGet200ResponseDataItemsInnerContentImage {
	if o == nil || IsNil(o.Image) {
		var ret ApiCampaignsGet200ResponseDataItemsInnerContentImage
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContent) GetImageOk() (*ApiCampaignsGet200ResponseDataItemsInnerContentImage, bool) {
	if o == nil || IsNil(o.Image) {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContent) HasImage() bool {
	if o != nil && !IsNil(o.Image) {
		return true
	}

	return false
}

// SetImage gets a reference to the given ApiCampaignsGet200ResponseDataItemsInnerContentImage and assigns it to the Image field.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContent) SetImage(v ApiCampaignsGet200ResponseDataItemsInnerContentImage) {
	o.Image = &v
}

// GetDetailLink returns the DetailLink field value if set, zero value otherwise.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContent) GetDetailLink() ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink {
	if o == nil || IsNil(o.DetailLink) {
		var ret ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink
		return ret
	}
	return *o.DetailLink
}

// GetDetailLinkOk returns a tuple with the DetailLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContent) GetDetailLinkOk() (*ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink, bool) {
	if o == nil || IsNil(o.DetailLink) {
		return nil, false
	}
	return o.DetailLink, true
}

// HasDetailLink returns a boolean if a field has been set.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContent) HasDetailLink() bool {
	if o != nil && !IsNil(o.DetailLink) {
		return true
	}

	return false
}

// SetDetailLink gets a reference to the given ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink and assigns it to the DetailLink field.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContent) SetDetailLink(v ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink) {
	o.DetailLink = &v
}

func (o ApiCampaignsGet200ResponseDataItemsInnerContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCampaignsGet200ResponseDataItemsInnerContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Image) {
		toSerialize["image"] = o.Image
	}
	if !IsNil(o.DetailLink) {
		toSerialize["detailLink"] = o.DetailLink
	}
	return toSerialize, nil
}

type NullableApiCampaignsGet200ResponseDataItemsInnerContent struct {
	value *ApiCampaignsGet200ResponseDataItemsInnerContent
	isSet bool
}

func (v NullableApiCampaignsGet200ResponseDataItemsInnerContent) Get() *ApiCampaignsGet200ResponseDataItemsInnerContent {
	return v.value
}

func (v *NullableApiCampaignsGet200ResponseDataItemsInnerContent) Set(val *ApiCampaignsGet200ResponseDataItemsInnerContent) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCampaignsGet200ResponseDataItemsInnerContent) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCampaignsGet200ResponseDataItemsInnerContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCampaignsGet200ResponseDataItemsInnerContent(val *ApiCampaignsGet200ResponseDataItemsInnerContent) *NullableApiCampaignsGet200ResponseDataItemsInnerContent {
	return &NullableApiCampaignsGet200ResponseDataItemsInnerContent{value: val, isSet: true}
}

func (v NullableApiCampaignsGet200ResponseDataItemsInnerContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCampaignsGet200ResponseDataItemsInnerContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


