/*
secure.scotiabank.com.har Mitmproxy2Swagger

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory{}

// ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory struct for ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory
type ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory struct {
	Code *string `json:"code,omitempty"`
	Description *string `json:"description,omitempty"`
}

// NewApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory instantiates a new ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory() *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory {
	this := ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory{}
	return &this
}

// NewApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategoryWithDefaults instantiates a new ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategoryWithDefaults() *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory {
	this := ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory) SetCode(v string) {
	o.Code = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory) SetDescription(v string) {
	o.Description = &v
}

func (o ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory struct {
	value *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory
	isSet bool
}

func (v NullableApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory) Get() *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory {
	return v.value
}

func (v *NullableApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory) Set(val *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory) {
	v.value = val
	v.isSet = true
}

func (v NullableApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory) IsSet() bool {
	return v.isSet
}

func (v *NullableApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory(val *ApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory) *NullableApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory {
	return &NullableApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory{value: val, isSet: true}
}

func (v NullableApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiTransactionsDepositAccountsDepositAccountIdGet200ResponseDataInnerCategory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


