/*
secure.scotiabank.com.har Mitmproxy2Swagger

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail{}

// ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail struct for ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail
type ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail struct {
	Total []ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner `json:"total,omitempty"`
	Assets []ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner `json:"assets,omitempty"`
	Liabilities []ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner `json:"liabilities,omitempty"`
}

// NewApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail instantiates a new ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail() *ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail {
	this := ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail{}
	return &this
}

// NewApiAccountsSummaryGet200ResponseDataCombinedBalancesRetailWithDefaults instantiates a new ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAccountsSummaryGet200ResponseDataCombinedBalancesRetailWithDefaults() *ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail {
	this := ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail) GetTotal() []ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner {
	if o == nil || IsNil(o.Total) {
		var ret []ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner
		return ret
	}
	return o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail) GetTotalOk() ([]ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given []ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner and assigns it to the Total field.
func (o *ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail) SetTotal(v []ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner) {
	o.Total = v
}

// GetAssets returns the Assets field value if set, zero value otherwise.
func (o *ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail) GetAssets() []ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner {
	if o == nil || IsNil(o.Assets) {
		var ret []ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner
		return ret
	}
	return o.Assets
}

// GetAssetsOk returns a tuple with the Assets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail) GetAssetsOk() ([]ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner, bool) {
	if o == nil || IsNil(o.Assets) {
		return nil, false
	}
	return o.Assets, true
}

// HasAssets returns a boolean if a field has been set.
func (o *ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail) HasAssets() bool {
	if o != nil && !IsNil(o.Assets) {
		return true
	}

	return false
}

// SetAssets gets a reference to the given []ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner and assigns it to the Assets field.
func (o *ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail) SetAssets(v []ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner) {
	o.Assets = v
}

// GetLiabilities returns the Liabilities field value if set, zero value otherwise.
func (o *ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail) GetLiabilities() []ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner {
	if o == nil || IsNil(o.Liabilities) {
		var ret []ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner
		return ret
	}
	return o.Liabilities
}

// GetLiabilitiesOk returns a tuple with the Liabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail) GetLiabilitiesOk() ([]ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner, bool) {
	if o == nil || IsNil(o.Liabilities) {
		return nil, false
	}
	return o.Liabilities, true
}

// HasLiabilities returns a boolean if a field has been set.
func (o *ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail) HasLiabilities() bool {
	if o != nil && !IsNil(o.Liabilities) {
		return true
	}

	return false
}

// SetLiabilities gets a reference to the given []ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner and assigns it to the Liabilities field.
func (o *ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail) SetLiabilities(v []ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner) {
	o.Liabilities = v
}

func (o ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Assets) {
		toSerialize["assets"] = o.Assets
	}
	if !IsNil(o.Liabilities) {
		toSerialize["liabilities"] = o.Liabilities
	}
	return toSerialize, nil
}

type NullableApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail struct {
	value *ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail
	isSet bool
}

func (v NullableApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail) Get() *ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail {
	return v.value
}

func (v *NullableApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail) Set(val *ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail(val *ApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail) *NullableApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail {
	return &NullableApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail{value: val, isSet: true}
}

func (v NullableApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAccountsSummaryGet200ResponseDataCombinedBalancesRetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


