/*
secure.scotiabank.com.har Mitmproxy2Swagger

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiCardsCardIdGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCardsCardIdGet200Response{}

// ApiCardsCardIdGet200Response struct for ApiCardsCardIdGet200Response
type ApiCardsCardIdGet200Response struct {
	Data *ApiCardsCardIdGet200ResponseData `json:"data,omitempty"`
	Notifications map[string]interface{} `json:"notifications,omitempty"`
}

// NewApiCardsCardIdGet200Response instantiates a new ApiCardsCardIdGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCardsCardIdGet200Response() *ApiCardsCardIdGet200Response {
	this := ApiCardsCardIdGet200Response{}
	return &this
}

// NewApiCardsCardIdGet200ResponseWithDefaults instantiates a new ApiCardsCardIdGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCardsCardIdGet200ResponseWithDefaults() *ApiCardsCardIdGet200Response {
	this := ApiCardsCardIdGet200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ApiCardsCardIdGet200Response) GetData() ApiCardsCardIdGet200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret ApiCardsCardIdGet200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCardsCardIdGet200Response) GetDataOk() (*ApiCardsCardIdGet200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ApiCardsCardIdGet200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ApiCardsCardIdGet200ResponseData and assigns it to the Data field.
func (o *ApiCardsCardIdGet200Response) SetData(v ApiCardsCardIdGet200ResponseData) {
	o.Data = &v
}

// GetNotifications returns the Notifications field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCardsCardIdGet200Response) GetNotifications() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Notifications
}

// GetNotificationsOk returns a tuple with the Notifications field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCardsCardIdGet200Response) GetNotificationsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Notifications) {
		return map[string]interface{}{}, false
	}
	return o.Notifications, true
}

// HasNotifications returns a boolean if a field has been set.
func (o *ApiCardsCardIdGet200Response) HasNotifications() bool {
	if o != nil && !IsNil(o.Notifications) {
		return true
	}

	return false
}

// SetNotifications gets a reference to the given map[string]interface{} and assigns it to the Notifications field.
func (o *ApiCardsCardIdGet200Response) SetNotifications(v map[string]interface{}) {
	o.Notifications = v
}

func (o ApiCardsCardIdGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCardsCardIdGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if o.Notifications != nil {
		toSerialize["notifications"] = o.Notifications
	}
	return toSerialize, nil
}

type NullableApiCardsCardIdGet200Response struct {
	value *ApiCardsCardIdGet200Response
	isSet bool
}

func (v NullableApiCardsCardIdGet200Response) Get() *ApiCardsCardIdGet200Response {
	return v.value
}

func (v *NullableApiCardsCardIdGet200Response) Set(val *ApiCardsCardIdGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCardsCardIdGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCardsCardIdGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCardsCardIdGet200Response(val *ApiCardsCardIdGet200Response) *NullableApiCardsCardIdGet200Response {
	return &NullableApiCardsCardIdGet200Response{value: val, isSet: true}
}

func (v NullableApiCardsCardIdGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCardsCardIdGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


