/*
secure.scotiabank.com.har Mitmproxy2Swagger

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiAccountsSummaryGet200ResponseDataProductsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAccountsSummaryGet200ResponseDataProductsInner{}

// ApiAccountsSummaryGet200ResponseDataProductsInner struct for ApiAccountsSummaryGet200ResponseDataProductsInner
type ApiAccountsSummaryGet200ResponseDataProductsInner struct {
	Key *string `json:"key,omitempty"`
	DisplayId *string `json:"displayId,omitempty"`
	ProductCategory *string `json:"productCategory,omitempty"`
	CiProductCode *string `json:"ciProductCode,omitempty"`
	CiSubProductCode *string `json:"ciSubProductCode,omitempty"`
	Type *string `json:"type,omitempty"`
	OwnershipType *string `json:"ownershipType,omitempty"`
	Description *string `json:"description,omitempty"`
	PrimaryBalances []ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner `json:"primaryBalances,omitempty"`
	RewardType *string `json:"rewardType,omitempty"`
	ShowBenefitsLink *bool `json:"showBenefitsLink,omitempty"`
	Disabled *bool `json:"disabled,omitempty"`
	Children []interface{} `json:"children,omitempty"`
}

// NewApiAccountsSummaryGet200ResponseDataProductsInner instantiates a new ApiAccountsSummaryGet200ResponseDataProductsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAccountsSummaryGet200ResponseDataProductsInner() *ApiAccountsSummaryGet200ResponseDataProductsInner {
	this := ApiAccountsSummaryGet200ResponseDataProductsInner{}
	return &this
}

// NewApiAccountsSummaryGet200ResponseDataProductsInnerWithDefaults instantiates a new ApiAccountsSummaryGet200ResponseDataProductsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAccountsSummaryGet200ResponseDataProductsInnerWithDefaults() *ApiAccountsSummaryGet200ResponseDataProductsInner {
	this := ApiAccountsSummaryGet200ResponseDataProductsInner{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) SetKey(v string) {
	o.Key = &v
}

// GetDisplayId returns the DisplayId field value if set, zero value otherwise.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) GetDisplayId() string {
	if o == nil || IsNil(o.DisplayId) {
		var ret string
		return ret
	}
	return *o.DisplayId
}

// GetDisplayIdOk returns a tuple with the DisplayId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) GetDisplayIdOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayId) {
		return nil, false
	}
	return o.DisplayId, true
}

// HasDisplayId returns a boolean if a field has been set.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) HasDisplayId() bool {
	if o != nil && !IsNil(o.DisplayId) {
		return true
	}

	return false
}

// SetDisplayId gets a reference to the given string and assigns it to the DisplayId field.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) SetDisplayId(v string) {
	o.DisplayId = &v
}

// GetProductCategory returns the ProductCategory field value if set, zero value otherwise.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) GetProductCategory() string {
	if o == nil || IsNil(o.ProductCategory) {
		var ret string
		return ret
	}
	return *o.ProductCategory
}

// GetProductCategoryOk returns a tuple with the ProductCategory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) GetProductCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.ProductCategory) {
		return nil, false
	}
	return o.ProductCategory, true
}

// HasProductCategory returns a boolean if a field has been set.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) HasProductCategory() bool {
	if o != nil && !IsNil(o.ProductCategory) {
		return true
	}

	return false
}

// SetProductCategory gets a reference to the given string and assigns it to the ProductCategory field.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) SetProductCategory(v string) {
	o.ProductCategory = &v
}

// GetCiProductCode returns the CiProductCode field value if set, zero value otherwise.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) GetCiProductCode() string {
	if o == nil || IsNil(o.CiProductCode) {
		var ret string
		return ret
	}
	return *o.CiProductCode
}

// GetCiProductCodeOk returns a tuple with the CiProductCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) GetCiProductCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CiProductCode) {
		return nil, false
	}
	return o.CiProductCode, true
}

// HasCiProductCode returns a boolean if a field has been set.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) HasCiProductCode() bool {
	if o != nil && !IsNil(o.CiProductCode) {
		return true
	}

	return false
}

// SetCiProductCode gets a reference to the given string and assigns it to the CiProductCode field.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) SetCiProductCode(v string) {
	o.CiProductCode = &v
}

// GetCiSubProductCode returns the CiSubProductCode field value if set, zero value otherwise.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) GetCiSubProductCode() string {
	if o == nil || IsNil(o.CiSubProductCode) {
		var ret string
		return ret
	}
	return *o.CiSubProductCode
}

// GetCiSubProductCodeOk returns a tuple with the CiSubProductCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) GetCiSubProductCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CiSubProductCode) {
		return nil, false
	}
	return o.CiSubProductCode, true
}

// HasCiSubProductCode returns a boolean if a field has been set.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) HasCiSubProductCode() bool {
	if o != nil && !IsNil(o.CiSubProductCode) {
		return true
	}

	return false
}

// SetCiSubProductCode gets a reference to the given string and assigns it to the CiSubProductCode field.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) SetCiSubProductCode(v string) {
	o.CiSubProductCode = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) SetType(v string) {
	o.Type = &v
}

// GetOwnershipType returns the OwnershipType field value if set, zero value otherwise.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) GetOwnershipType() string {
	if o == nil || IsNil(o.OwnershipType) {
		var ret string
		return ret
	}
	return *o.OwnershipType
}

// GetOwnershipTypeOk returns a tuple with the OwnershipType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) GetOwnershipTypeOk() (*string, bool) {
	if o == nil || IsNil(o.OwnershipType) {
		return nil, false
	}
	return o.OwnershipType, true
}

// HasOwnershipType returns a boolean if a field has been set.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) HasOwnershipType() bool {
	if o != nil && !IsNil(o.OwnershipType) {
		return true
	}

	return false
}

// SetOwnershipType gets a reference to the given string and assigns it to the OwnershipType field.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) SetOwnershipType(v string) {
	o.OwnershipType = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) SetDescription(v string) {
	o.Description = &v
}

// GetPrimaryBalances returns the PrimaryBalances field value if set, zero value otherwise.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) GetPrimaryBalances() []ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner {
	if o == nil || IsNil(o.PrimaryBalances) {
		var ret []ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner
		return ret
	}
	return o.PrimaryBalances
}

// GetPrimaryBalancesOk returns a tuple with the PrimaryBalances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) GetPrimaryBalancesOk() ([]ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner, bool) {
	if o == nil || IsNil(o.PrimaryBalances) {
		return nil, false
	}
	return o.PrimaryBalances, true
}

// HasPrimaryBalances returns a boolean if a field has been set.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) HasPrimaryBalances() bool {
	if o != nil && !IsNil(o.PrimaryBalances) {
		return true
	}

	return false
}

// SetPrimaryBalances gets a reference to the given []ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner and assigns it to the PrimaryBalances field.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) SetPrimaryBalances(v []ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner) {
	o.PrimaryBalances = v
}

// GetRewardType returns the RewardType field value if set, zero value otherwise.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) GetRewardType() string {
	if o == nil || IsNil(o.RewardType) {
		var ret string
		return ret
	}
	return *o.RewardType
}

// GetRewardTypeOk returns a tuple with the RewardType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) GetRewardTypeOk() (*string, bool) {
	if o == nil || IsNil(o.RewardType) {
		return nil, false
	}
	return o.RewardType, true
}

// HasRewardType returns a boolean if a field has been set.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) HasRewardType() bool {
	if o != nil && !IsNil(o.RewardType) {
		return true
	}

	return false
}

// SetRewardType gets a reference to the given string and assigns it to the RewardType field.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) SetRewardType(v string) {
	o.RewardType = &v
}

// GetShowBenefitsLink returns the ShowBenefitsLink field value if set, zero value otherwise.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) GetShowBenefitsLink() bool {
	if o == nil || IsNil(o.ShowBenefitsLink) {
		var ret bool
		return ret
	}
	return *o.ShowBenefitsLink
}

// GetShowBenefitsLinkOk returns a tuple with the ShowBenefitsLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) GetShowBenefitsLinkOk() (*bool, bool) {
	if o == nil || IsNil(o.ShowBenefitsLink) {
		return nil, false
	}
	return o.ShowBenefitsLink, true
}

// HasShowBenefitsLink returns a boolean if a field has been set.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) HasShowBenefitsLink() bool {
	if o != nil && !IsNil(o.ShowBenefitsLink) {
		return true
	}

	return false
}

// SetShowBenefitsLink gets a reference to the given bool and assigns it to the ShowBenefitsLink field.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) SetShowBenefitsLink(v bool) {
	o.ShowBenefitsLink = &v
}

// GetDisabled returns the Disabled field value if set, zero value otherwise.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) GetDisabled() bool {
	if o == nil || IsNil(o.Disabled) {
		var ret bool
		return ret
	}
	return *o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) GetDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Disabled) {
		return nil, false
	}
	return o.Disabled, true
}

// HasDisabled returns a boolean if a field has been set.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) HasDisabled() bool {
	if o != nil && !IsNil(o.Disabled) {
		return true
	}

	return false
}

// SetDisabled gets a reference to the given bool and assigns it to the Disabled field.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) SetDisabled(v bool) {
	o.Disabled = &v
}

// GetChildren returns the Children field value if set, zero value otherwise.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) GetChildren() []interface{} {
	if o == nil || IsNil(o.Children) {
		var ret []interface{}
		return ret
	}
	return o.Children
}

// GetChildrenOk returns a tuple with the Children field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) GetChildrenOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.Children) {
		return nil, false
	}
	return o.Children, true
}

// HasChildren returns a boolean if a field has been set.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) HasChildren() bool {
	if o != nil && !IsNil(o.Children) {
		return true
	}

	return false
}

// SetChildren gets a reference to the given []interface{} and assigns it to the Children field.
func (o *ApiAccountsSummaryGet200ResponseDataProductsInner) SetChildren(v []interface{}) {
	o.Children = v
}

func (o ApiAccountsSummaryGet200ResponseDataProductsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAccountsSummaryGet200ResponseDataProductsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.DisplayId) {
		toSerialize["displayId"] = o.DisplayId
	}
	if !IsNil(o.ProductCategory) {
		toSerialize["productCategory"] = o.ProductCategory
	}
	if !IsNil(o.CiProductCode) {
		toSerialize["ciProductCode"] = o.CiProductCode
	}
	if !IsNil(o.CiSubProductCode) {
		toSerialize["ciSubProductCode"] = o.CiSubProductCode
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.OwnershipType) {
		toSerialize["ownershipType"] = o.OwnershipType
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.PrimaryBalances) {
		toSerialize["primaryBalances"] = o.PrimaryBalances
	}
	if !IsNil(o.RewardType) {
		toSerialize["rewardType"] = o.RewardType
	}
	if !IsNil(o.ShowBenefitsLink) {
		toSerialize["showBenefitsLink"] = o.ShowBenefitsLink
	}
	if !IsNil(o.Disabled) {
		toSerialize["disabled"] = o.Disabled
	}
	if !IsNil(o.Children) {
		toSerialize["children"] = o.Children
	}
	return toSerialize, nil
}

type NullableApiAccountsSummaryGet200ResponseDataProductsInner struct {
	value *ApiAccountsSummaryGet200ResponseDataProductsInner
	isSet bool
}

func (v NullableApiAccountsSummaryGet200ResponseDataProductsInner) Get() *ApiAccountsSummaryGet200ResponseDataProductsInner {
	return v.value
}

func (v *NullableApiAccountsSummaryGet200ResponseDataProductsInner) Set(val *ApiAccountsSummaryGet200ResponseDataProductsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAccountsSummaryGet200ResponseDataProductsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAccountsSummaryGet200ResponseDataProductsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAccountsSummaryGet200ResponseDataProductsInner(val *ApiAccountsSummaryGet200ResponseDataProductsInner) *NullableApiAccountsSummaryGet200ResponseDataProductsInner {
	return &NullableApiAccountsSummaryGet200ResponseDataProductsInner{value: val, isSet: true}
}

func (v NullableApiAccountsSummaryGet200ResponseDataProductsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAccountsSummaryGet200ResponseDataProductsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


