/*
secure.scotiabank.com.har Mitmproxy2Swagger

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant{}

// ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant struct for ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant
type ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant struct {
	Name *string `json:"name,omitempty"`
	CategoryCode *string `json:"categoryCode,omitempty"`
	Category NullableString `json:"category,omitempty"`
	CountryCode *string `json:"countryCode,omitempty"`
	Address NullableString `json:"address,omitempty"`
	City *string `json:"city,omitempty"`
	State *string `json:"state,omitempty"`
	Country NullableString `json:"country,omitempty"`
	ZipCode NullableString `json:"zipCode,omitempty"`
	Website NullableString `json:"website,omitempty"`
	CustomerServicePageUrl NullableString `json:"customerServicePageUrl,omitempty"`
	FacebookPageUrl NullableString `json:"facebookPageUrl,omitempty"`
	TwitterPageUrl NullableString `json:"twitterPageUrl,omitempty"`
	MerchantImageRef NullableString `json:"merchantImageRef,omitempty"`
}

// NewApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant instantiates a new ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant() *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant {
	this := ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant{}
	return &this
}

// NewApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchantWithDefaults instantiates a new ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchantWithDefaults() *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant {
	this := ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) SetName(v string) {
	o.Name = &v
}

// GetCategoryCode returns the CategoryCode field value if set, zero value otherwise.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) GetCategoryCode() string {
	if o == nil || IsNil(o.CategoryCode) {
		var ret string
		return ret
	}
	return *o.CategoryCode
}

// GetCategoryCodeOk returns a tuple with the CategoryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) GetCategoryCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CategoryCode) {
		return nil, false
	}
	return o.CategoryCode, true
}

// HasCategoryCode returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) HasCategoryCode() bool {
	if o != nil && !IsNil(o.CategoryCode) {
		return true
	}

	return false
}

// SetCategoryCode gets a reference to the given string and assigns it to the CategoryCode field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) SetCategoryCode(v string) {
	o.CategoryCode = &v
}

// GetCategory returns the Category field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) GetCategory() string {
	if o == nil || IsNil(o.Category.Get()) {
		var ret string
		return ret
	}
	return *o.Category.Get()
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) GetCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Category.Get(), o.Category.IsSet()
}

// HasCategory returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) HasCategory() bool {
	if o != nil && o.Category.IsSet() {
		return true
	}

	return false
}

// SetCategory gets a reference to the given NullableString and assigns it to the Category field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) SetCategory(v string) {
	o.Category.Set(&v)
}
// SetCategoryNil sets the value for Category to be an explicit nil
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) SetCategoryNil() {
	o.Category.Set(nil)
}

// UnsetCategory ensures that no value is present for Category, not even an explicit nil
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) UnsetCategory() {
	o.Category.Unset()
}

// GetCountryCode returns the CountryCode field value if set, zero value otherwise.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) GetCountryCode() string {
	if o == nil || IsNil(o.CountryCode) {
		var ret string
		return ret
	}
	return *o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) GetCountryCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CountryCode) {
		return nil, false
	}
	return o.CountryCode, true
}

// HasCountryCode returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) HasCountryCode() bool {
	if o != nil && !IsNil(o.CountryCode) {
		return true
	}

	return false
}

// SetCountryCode gets a reference to the given string and assigns it to the CountryCode field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) SetCountryCode(v string) {
	o.CountryCode = &v
}

// GetAddress returns the Address field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) GetAddress() string {
	if o == nil || IsNil(o.Address.Get()) {
		var ret string
		return ret
	}
	return *o.Address.Get()
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Address.Get(), o.Address.IsSet()
}

// HasAddress returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) HasAddress() bool {
	if o != nil && o.Address.IsSet() {
		return true
	}

	return false
}

// SetAddress gets a reference to the given NullableString and assigns it to the Address field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) SetAddress(v string) {
	o.Address.Set(&v)
}
// SetAddressNil sets the value for Address to be an explicit nil
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) SetAddressNil() {
	o.Address.Set(nil)
}

// UnsetAddress ensures that no value is present for Address, not even an explicit nil
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) UnsetAddress() {
	o.Address.Unset()
}

// GetCity returns the City field value if set, zero value otherwise.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) GetCity() string {
	if o == nil || IsNil(o.City) {
		var ret string
		return ret
	}
	return *o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) GetCityOk() (*string, bool) {
	if o == nil || IsNil(o.City) {
		return nil, false
	}
	return o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) HasCity() bool {
	if o != nil && !IsNil(o.City) {
		return true
	}

	return false
}

// SetCity gets a reference to the given string and assigns it to the City field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) SetCity(v string) {
	o.City = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) SetState(v string) {
	o.State = &v
}

// GetCountry returns the Country field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) GetCountry() string {
	if o == nil || IsNil(o.Country.Get()) {
		var ret string
		return ret
	}
	return *o.Country.Get()
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Country.Get(), o.Country.IsSet()
}

// HasCountry returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) HasCountry() bool {
	if o != nil && o.Country.IsSet() {
		return true
	}

	return false
}

// SetCountry gets a reference to the given NullableString and assigns it to the Country field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) SetCountry(v string) {
	o.Country.Set(&v)
}
// SetCountryNil sets the value for Country to be an explicit nil
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) SetCountryNil() {
	o.Country.Set(nil)
}

// UnsetCountry ensures that no value is present for Country, not even an explicit nil
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) UnsetCountry() {
	o.Country.Unset()
}

// GetZipCode returns the ZipCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) GetZipCode() string {
	if o == nil || IsNil(o.ZipCode.Get()) {
		var ret string
		return ret
	}
	return *o.ZipCode.Get()
}

// GetZipCodeOk returns a tuple with the ZipCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) GetZipCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ZipCode.Get(), o.ZipCode.IsSet()
}

// HasZipCode returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) HasZipCode() bool {
	if o != nil && o.ZipCode.IsSet() {
		return true
	}

	return false
}

// SetZipCode gets a reference to the given NullableString and assigns it to the ZipCode field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) SetZipCode(v string) {
	o.ZipCode.Set(&v)
}
// SetZipCodeNil sets the value for ZipCode to be an explicit nil
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) SetZipCodeNil() {
	o.ZipCode.Set(nil)
}

// UnsetZipCode ensures that no value is present for ZipCode, not even an explicit nil
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) UnsetZipCode() {
	o.ZipCode.Unset()
}

// GetWebsite returns the Website field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) GetWebsite() string {
	if o == nil || IsNil(o.Website.Get()) {
		var ret string
		return ret
	}
	return *o.Website.Get()
}

// GetWebsiteOk returns a tuple with the Website field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) GetWebsiteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Website.Get(), o.Website.IsSet()
}

// HasWebsite returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) HasWebsite() bool {
	if o != nil && o.Website.IsSet() {
		return true
	}

	return false
}

// SetWebsite gets a reference to the given NullableString and assigns it to the Website field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) SetWebsite(v string) {
	o.Website.Set(&v)
}
// SetWebsiteNil sets the value for Website to be an explicit nil
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) SetWebsiteNil() {
	o.Website.Set(nil)
}

// UnsetWebsite ensures that no value is present for Website, not even an explicit nil
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) UnsetWebsite() {
	o.Website.Unset()
}

// GetCustomerServicePageUrl returns the CustomerServicePageUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) GetCustomerServicePageUrl() string {
	if o == nil || IsNil(o.CustomerServicePageUrl.Get()) {
		var ret string
		return ret
	}
	return *o.CustomerServicePageUrl.Get()
}

// GetCustomerServicePageUrlOk returns a tuple with the CustomerServicePageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) GetCustomerServicePageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomerServicePageUrl.Get(), o.CustomerServicePageUrl.IsSet()
}

// HasCustomerServicePageUrl returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) HasCustomerServicePageUrl() bool {
	if o != nil && o.CustomerServicePageUrl.IsSet() {
		return true
	}

	return false
}

// SetCustomerServicePageUrl gets a reference to the given NullableString and assigns it to the CustomerServicePageUrl field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) SetCustomerServicePageUrl(v string) {
	o.CustomerServicePageUrl.Set(&v)
}
// SetCustomerServicePageUrlNil sets the value for CustomerServicePageUrl to be an explicit nil
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) SetCustomerServicePageUrlNil() {
	o.CustomerServicePageUrl.Set(nil)
}

// UnsetCustomerServicePageUrl ensures that no value is present for CustomerServicePageUrl, not even an explicit nil
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) UnsetCustomerServicePageUrl() {
	o.CustomerServicePageUrl.Unset()
}

// GetFacebookPageUrl returns the FacebookPageUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) GetFacebookPageUrl() string {
	if o == nil || IsNil(o.FacebookPageUrl.Get()) {
		var ret string
		return ret
	}
	return *o.FacebookPageUrl.Get()
}

// GetFacebookPageUrlOk returns a tuple with the FacebookPageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) GetFacebookPageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FacebookPageUrl.Get(), o.FacebookPageUrl.IsSet()
}

// HasFacebookPageUrl returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) HasFacebookPageUrl() bool {
	if o != nil && o.FacebookPageUrl.IsSet() {
		return true
	}

	return false
}

// SetFacebookPageUrl gets a reference to the given NullableString and assigns it to the FacebookPageUrl field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) SetFacebookPageUrl(v string) {
	o.FacebookPageUrl.Set(&v)
}
// SetFacebookPageUrlNil sets the value for FacebookPageUrl to be an explicit nil
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) SetFacebookPageUrlNil() {
	o.FacebookPageUrl.Set(nil)
}

// UnsetFacebookPageUrl ensures that no value is present for FacebookPageUrl, not even an explicit nil
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) UnsetFacebookPageUrl() {
	o.FacebookPageUrl.Unset()
}

// GetTwitterPageUrl returns the TwitterPageUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) GetTwitterPageUrl() string {
	if o == nil || IsNil(o.TwitterPageUrl.Get()) {
		var ret string
		return ret
	}
	return *o.TwitterPageUrl.Get()
}

// GetTwitterPageUrlOk returns a tuple with the TwitterPageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) GetTwitterPageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TwitterPageUrl.Get(), o.TwitterPageUrl.IsSet()
}

// HasTwitterPageUrl returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) HasTwitterPageUrl() bool {
	if o != nil && o.TwitterPageUrl.IsSet() {
		return true
	}

	return false
}

// SetTwitterPageUrl gets a reference to the given NullableString and assigns it to the TwitterPageUrl field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) SetTwitterPageUrl(v string) {
	o.TwitterPageUrl.Set(&v)
}
// SetTwitterPageUrlNil sets the value for TwitterPageUrl to be an explicit nil
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) SetTwitterPageUrlNil() {
	o.TwitterPageUrl.Set(nil)
}

// UnsetTwitterPageUrl ensures that no value is present for TwitterPageUrl, not even an explicit nil
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) UnsetTwitterPageUrl() {
	o.TwitterPageUrl.Unset()
}

// GetMerchantImageRef returns the MerchantImageRef field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) GetMerchantImageRef() string {
	if o == nil || IsNil(o.MerchantImageRef.Get()) {
		var ret string
		return ret
	}
	return *o.MerchantImageRef.Get()
}

// GetMerchantImageRefOk returns a tuple with the MerchantImageRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) GetMerchantImageRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MerchantImageRef.Get(), o.MerchantImageRef.IsSet()
}

// HasMerchantImageRef returns a boolean if a field has been set.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) HasMerchantImageRef() bool {
	if o != nil && o.MerchantImageRef.IsSet() {
		return true
	}

	return false
}

// SetMerchantImageRef gets a reference to the given NullableString and assigns it to the MerchantImageRef field.
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) SetMerchantImageRef(v string) {
	o.MerchantImageRef.Set(&v)
}
// SetMerchantImageRefNil sets the value for MerchantImageRef to be an explicit nil
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) SetMerchantImageRefNil() {
	o.MerchantImageRef.Set(nil)
}

// UnsetMerchantImageRef ensures that no value is present for MerchantImageRef, not even an explicit nil
func (o *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) UnsetMerchantImageRef() {
	o.MerchantImageRef.Unset()
}

func (o ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.CategoryCode) {
		toSerialize["categoryCode"] = o.CategoryCode
	}
	if o.Category.IsSet() {
		toSerialize["category"] = o.Category.Get()
	}
	if !IsNil(o.CountryCode) {
		toSerialize["countryCode"] = o.CountryCode
	}
	if o.Address.IsSet() {
		toSerialize["address"] = o.Address.Get()
	}
	if !IsNil(o.City) {
		toSerialize["city"] = o.City
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if o.Country.IsSet() {
		toSerialize["country"] = o.Country.Get()
	}
	if o.ZipCode.IsSet() {
		toSerialize["zipCode"] = o.ZipCode.Get()
	}
	if o.Website.IsSet() {
		toSerialize["website"] = o.Website.Get()
	}
	if o.CustomerServicePageUrl.IsSet() {
		toSerialize["customerServicePageUrl"] = o.CustomerServicePageUrl.Get()
	}
	if o.FacebookPageUrl.IsSet() {
		toSerialize["facebookPageUrl"] = o.FacebookPageUrl.Get()
	}
	if o.TwitterPageUrl.IsSet() {
		toSerialize["twitterPageUrl"] = o.TwitterPageUrl.Get()
	}
	if o.MerchantImageRef.IsSet() {
		toSerialize["merchantImageRef"] = o.MerchantImageRef.Get()
	}
	return toSerialize, nil
}

type NullableApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant struct {
	value *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant
	isSet bool
}

func (v NullableApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) Get() *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant {
	return v.value
}

func (v *NullableApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) Set(val *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant(val *ApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) *NullableApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant {
	return &NullableApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant{value: val, isSet: true}
}

func (v NullableApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCreditCreditIdTransactionsGet200ResponseDataSettledInnerMerchant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


