/*
secure.scotiabank.com.har Mitmproxy2Swagger

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiRewardsRewardIdGet200ResponseDataAccountsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiRewardsRewardIdGet200ResponseDataAccountsInner{}

// ApiRewardsRewardIdGet200ResponseDataAccountsInner struct for ApiRewardsRewardIdGet200ResponseDataAccountsInner
type ApiRewardsRewardIdGet200ResponseDataAccountsInner struct {
	AccountKey *string `json:"accountKey,omitempty"`
	AccountDescription *string `json:"accountDescription,omitempty"`
	AccountType *string `json:"accountType,omitempty"`
	CardNo *string `json:"cardNo,omitempty"`
	PointsBalance *float32 `json:"pointsBalance,omitempty"`
}

// NewApiRewardsRewardIdGet200ResponseDataAccountsInner instantiates a new ApiRewardsRewardIdGet200ResponseDataAccountsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiRewardsRewardIdGet200ResponseDataAccountsInner() *ApiRewardsRewardIdGet200ResponseDataAccountsInner {
	this := ApiRewardsRewardIdGet200ResponseDataAccountsInner{}
	return &this
}

// NewApiRewardsRewardIdGet200ResponseDataAccountsInnerWithDefaults instantiates a new ApiRewardsRewardIdGet200ResponseDataAccountsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiRewardsRewardIdGet200ResponseDataAccountsInnerWithDefaults() *ApiRewardsRewardIdGet200ResponseDataAccountsInner {
	this := ApiRewardsRewardIdGet200ResponseDataAccountsInner{}
	return &this
}

// GetAccountKey returns the AccountKey field value if set, zero value otherwise.
func (o *ApiRewardsRewardIdGet200ResponseDataAccountsInner) GetAccountKey() string {
	if o == nil || IsNil(o.AccountKey) {
		var ret string
		return ret
	}
	return *o.AccountKey
}

// GetAccountKeyOk returns a tuple with the AccountKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiRewardsRewardIdGet200ResponseDataAccountsInner) GetAccountKeyOk() (*string, bool) {
	if o == nil || IsNil(o.AccountKey) {
		return nil, false
	}
	return o.AccountKey, true
}

// HasAccountKey returns a boolean if a field has been set.
func (o *ApiRewardsRewardIdGet200ResponseDataAccountsInner) HasAccountKey() bool {
	if o != nil && !IsNil(o.AccountKey) {
		return true
	}

	return false
}

// SetAccountKey gets a reference to the given string and assigns it to the AccountKey field.
func (o *ApiRewardsRewardIdGet200ResponseDataAccountsInner) SetAccountKey(v string) {
	o.AccountKey = &v
}

// GetAccountDescription returns the AccountDescription field value if set, zero value otherwise.
func (o *ApiRewardsRewardIdGet200ResponseDataAccountsInner) GetAccountDescription() string {
	if o == nil || IsNil(o.AccountDescription) {
		var ret string
		return ret
	}
	return *o.AccountDescription
}

// GetAccountDescriptionOk returns a tuple with the AccountDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiRewardsRewardIdGet200ResponseDataAccountsInner) GetAccountDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.AccountDescription) {
		return nil, false
	}
	return o.AccountDescription, true
}

// HasAccountDescription returns a boolean if a field has been set.
func (o *ApiRewardsRewardIdGet200ResponseDataAccountsInner) HasAccountDescription() bool {
	if o != nil && !IsNil(o.AccountDescription) {
		return true
	}

	return false
}

// SetAccountDescription gets a reference to the given string and assigns it to the AccountDescription field.
func (o *ApiRewardsRewardIdGet200ResponseDataAccountsInner) SetAccountDescription(v string) {
	o.AccountDescription = &v
}

// GetAccountType returns the AccountType field value if set, zero value otherwise.
func (o *ApiRewardsRewardIdGet200ResponseDataAccountsInner) GetAccountType() string {
	if o == nil || IsNil(o.AccountType) {
		var ret string
		return ret
	}
	return *o.AccountType
}

// GetAccountTypeOk returns a tuple with the AccountType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiRewardsRewardIdGet200ResponseDataAccountsInner) GetAccountTypeOk() (*string, bool) {
	if o == nil || IsNil(o.AccountType) {
		return nil, false
	}
	return o.AccountType, true
}

// HasAccountType returns a boolean if a field has been set.
func (o *ApiRewardsRewardIdGet200ResponseDataAccountsInner) HasAccountType() bool {
	if o != nil && !IsNil(o.AccountType) {
		return true
	}

	return false
}

// SetAccountType gets a reference to the given string and assigns it to the AccountType field.
func (o *ApiRewardsRewardIdGet200ResponseDataAccountsInner) SetAccountType(v string) {
	o.AccountType = &v
}

// GetCardNo returns the CardNo field value if set, zero value otherwise.
func (o *ApiRewardsRewardIdGet200ResponseDataAccountsInner) GetCardNo() string {
	if o == nil || IsNil(o.CardNo) {
		var ret string
		return ret
	}
	return *o.CardNo
}

// GetCardNoOk returns a tuple with the CardNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiRewardsRewardIdGet200ResponseDataAccountsInner) GetCardNoOk() (*string, bool) {
	if o == nil || IsNil(o.CardNo) {
		return nil, false
	}
	return o.CardNo, true
}

// HasCardNo returns a boolean if a field has been set.
func (o *ApiRewardsRewardIdGet200ResponseDataAccountsInner) HasCardNo() bool {
	if o != nil && !IsNil(o.CardNo) {
		return true
	}

	return false
}

// SetCardNo gets a reference to the given string and assigns it to the CardNo field.
func (o *ApiRewardsRewardIdGet200ResponseDataAccountsInner) SetCardNo(v string) {
	o.CardNo = &v
}

// GetPointsBalance returns the PointsBalance field value if set, zero value otherwise.
func (o *ApiRewardsRewardIdGet200ResponseDataAccountsInner) GetPointsBalance() float32 {
	if o == nil || IsNil(o.PointsBalance) {
		var ret float32
		return ret
	}
	return *o.PointsBalance
}

// GetPointsBalanceOk returns a tuple with the PointsBalance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiRewardsRewardIdGet200ResponseDataAccountsInner) GetPointsBalanceOk() (*float32, bool) {
	if o == nil || IsNil(o.PointsBalance) {
		return nil, false
	}
	return o.PointsBalance, true
}

// HasPointsBalance returns a boolean if a field has been set.
func (o *ApiRewardsRewardIdGet200ResponseDataAccountsInner) HasPointsBalance() bool {
	if o != nil && !IsNil(o.PointsBalance) {
		return true
	}

	return false
}

// SetPointsBalance gets a reference to the given float32 and assigns it to the PointsBalance field.
func (o *ApiRewardsRewardIdGet200ResponseDataAccountsInner) SetPointsBalance(v float32) {
	o.PointsBalance = &v
}

func (o ApiRewardsRewardIdGet200ResponseDataAccountsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiRewardsRewardIdGet200ResponseDataAccountsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountKey) {
		toSerialize["accountKey"] = o.AccountKey
	}
	if !IsNil(o.AccountDescription) {
		toSerialize["accountDescription"] = o.AccountDescription
	}
	if !IsNil(o.AccountType) {
		toSerialize["accountType"] = o.AccountType
	}
	if !IsNil(o.CardNo) {
		toSerialize["cardNo"] = o.CardNo
	}
	if !IsNil(o.PointsBalance) {
		toSerialize["pointsBalance"] = o.PointsBalance
	}
	return toSerialize, nil
}

type NullableApiRewardsRewardIdGet200ResponseDataAccountsInner struct {
	value *ApiRewardsRewardIdGet200ResponseDataAccountsInner
	isSet bool
}

func (v NullableApiRewardsRewardIdGet200ResponseDataAccountsInner) Get() *ApiRewardsRewardIdGet200ResponseDataAccountsInner {
	return v.value
}

func (v *NullableApiRewardsRewardIdGet200ResponseDataAccountsInner) Set(val *ApiRewardsRewardIdGet200ResponseDataAccountsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableApiRewardsRewardIdGet200ResponseDataAccountsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableApiRewardsRewardIdGet200ResponseDataAccountsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiRewardsRewardIdGet200ResponseDataAccountsInner(val *ApiRewardsRewardIdGet200ResponseDataAccountsInner) *NullableApiRewardsRewardIdGet200ResponseDataAccountsInner {
	return &NullableApiRewardsRewardIdGet200ResponseDataAccountsInner{value: val, isSet: true}
}

func (v NullableApiRewardsRewardIdGet200ResponseDataAccountsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiRewardsRewardIdGet200ResponseDataAccountsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


