/*
secure.scotiabank.com.har Mitmproxy2Swagger

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility{}

// ApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility struct for ApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility
type ApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility struct {
	IsEnrolled *bool `json:"isEnrolled,omitempty"`
	HasPlans *bool `json:"hasPlans,omitempty"`
}

// NewApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility instantiates a new ApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility() *ApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility {
	this := ApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility{}
	return &this
}

// NewApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibilityWithDefaults instantiates a new ApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibilityWithDefaults() *ApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility {
	this := ApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility{}
	return &this
}

// GetIsEnrolled returns the IsEnrolled field value if set, zero value otherwise.
func (o *ApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility) GetIsEnrolled() bool {
	if o == nil || IsNil(o.IsEnrolled) {
		var ret bool
		return ret
	}
	return *o.IsEnrolled
}

// GetIsEnrolledOk returns a tuple with the IsEnrolled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility) GetIsEnrolledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsEnrolled) {
		return nil, false
	}
	return o.IsEnrolled, true
}

// HasIsEnrolled returns a boolean if a field has been set.
func (o *ApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility) HasIsEnrolled() bool {
	if o != nil && !IsNil(o.IsEnrolled) {
		return true
	}

	return false
}

// SetIsEnrolled gets a reference to the given bool and assigns it to the IsEnrolled field.
func (o *ApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility) SetIsEnrolled(v bool) {
	o.IsEnrolled = &v
}

// GetHasPlans returns the HasPlans field value if set, zero value otherwise.
func (o *ApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility) GetHasPlans() bool {
	if o == nil || IsNil(o.HasPlans) {
		var ret bool
		return ret
	}
	return *o.HasPlans
}

// GetHasPlansOk returns a tuple with the HasPlans field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility) GetHasPlansOk() (*bool, bool) {
	if o == nil || IsNil(o.HasPlans) {
		return nil, false
	}
	return o.HasPlans, true
}

// HasHasPlans returns a boolean if a field has been set.
func (o *ApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility) HasHasPlans() bool {
	if o != nil && !IsNil(o.HasPlans) {
		return true
	}

	return false
}

// SetHasPlans gets a reference to the given bool and assigns it to the HasPlans field.
func (o *ApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility) SetHasPlans(v bool) {
	o.HasPlans = &v
}

func (o ApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IsEnrolled) {
		toSerialize["isEnrolled"] = o.IsEnrolled
	}
	if !IsNil(o.HasPlans) {
		toSerialize["hasPlans"] = o.HasPlans
	}
	return toSerialize, nil
}

type NullableApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility struct {
	value *ApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility
	isSet bool
}

func (v NullableApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility) Get() *ApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility {
	return v.value
}

func (v *NullableApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility) Set(val *ApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility(val *ApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility) *NullableApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility {
	return &NullableApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility{value: val, isSet: true}
}

func (v NullableApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCreditCreditIdGet200ResponseDataInstallmentPlanEligibility) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


