/*
secure.scotiabank.com.har Mitmproxy2Swagger

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiRewardsRewardIdGet400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiRewardsRewardIdGet400Response{}

// ApiRewardsRewardIdGet400Response struct for ApiRewardsRewardIdGet400Response
type ApiRewardsRewardIdGet400Response struct {
	Notifications []ApiRewardsRewardIdGet400ResponseNotificationsInner `json:"notifications,omitempty"`
}

// NewApiRewardsRewardIdGet400Response instantiates a new ApiRewardsRewardIdGet400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiRewardsRewardIdGet400Response() *ApiRewardsRewardIdGet400Response {
	this := ApiRewardsRewardIdGet400Response{}
	return &this
}

// NewApiRewardsRewardIdGet400ResponseWithDefaults instantiates a new ApiRewardsRewardIdGet400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiRewardsRewardIdGet400ResponseWithDefaults() *ApiRewardsRewardIdGet400Response {
	this := ApiRewardsRewardIdGet400Response{}
	return &this
}

// GetNotifications returns the Notifications field value if set, zero value otherwise.
func (o *ApiRewardsRewardIdGet400Response) GetNotifications() []ApiRewardsRewardIdGet400ResponseNotificationsInner {
	if o == nil || IsNil(o.Notifications) {
		var ret []ApiRewardsRewardIdGet400ResponseNotificationsInner
		return ret
	}
	return o.Notifications
}

// GetNotificationsOk returns a tuple with the Notifications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiRewardsRewardIdGet400Response) GetNotificationsOk() ([]ApiRewardsRewardIdGet400ResponseNotificationsInner, bool) {
	if o == nil || IsNil(o.Notifications) {
		return nil, false
	}
	return o.Notifications, true
}

// HasNotifications returns a boolean if a field has been set.
func (o *ApiRewardsRewardIdGet400Response) HasNotifications() bool {
	if o != nil && !IsNil(o.Notifications) {
		return true
	}

	return false
}

// SetNotifications gets a reference to the given []ApiRewardsRewardIdGet400ResponseNotificationsInner and assigns it to the Notifications field.
func (o *ApiRewardsRewardIdGet400Response) SetNotifications(v []ApiRewardsRewardIdGet400ResponseNotificationsInner) {
	o.Notifications = v
}

func (o ApiRewardsRewardIdGet400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiRewardsRewardIdGet400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Notifications) {
		toSerialize["notifications"] = o.Notifications
	}
	return toSerialize, nil
}

type NullableApiRewardsRewardIdGet400Response struct {
	value *ApiRewardsRewardIdGet400Response
	isSet bool
}

func (v NullableApiRewardsRewardIdGet400Response) Get() *ApiRewardsRewardIdGet400Response {
	return v.value
}

func (v *NullableApiRewardsRewardIdGet400Response) Set(val *ApiRewardsRewardIdGet400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiRewardsRewardIdGet400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiRewardsRewardIdGet400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiRewardsRewardIdGet400Response(val *ApiRewardsRewardIdGet400Response) *NullableApiRewardsRewardIdGet400Response {
	return &NullableApiRewardsRewardIdGet400Response{value: val, isSet: true}
}

func (v NullableApiRewardsRewardIdGet400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiRewardsRewardIdGet400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


