/*
secure.scotiabank.com.har Mitmproxy2Swagger

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink{}

// ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink struct for ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink
type ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink struct {
	Text *string `json:"text,omitempty"`
	AriaLabel *string `json:"ariaLabel,omitempty"`
}

// NewApiCampaignsGet200ResponseDataItemsInnerContentDetailLink instantiates a new ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCampaignsGet200ResponseDataItemsInnerContentDetailLink() *ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink {
	this := ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink{}
	return &this
}

// NewApiCampaignsGet200ResponseDataItemsInnerContentDetailLinkWithDefaults instantiates a new ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCampaignsGet200ResponseDataItemsInnerContentDetailLinkWithDefaults() *ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink {
	this := ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink{}
	return &this
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink) SetText(v string) {
	o.Text = &v
}

// GetAriaLabel returns the AriaLabel field value if set, zero value otherwise.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink) GetAriaLabel() string {
	if o == nil || IsNil(o.AriaLabel) {
		var ret string
		return ret
	}
	return *o.AriaLabel
}

// GetAriaLabelOk returns a tuple with the AriaLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink) GetAriaLabelOk() (*string, bool) {
	if o == nil || IsNil(o.AriaLabel) {
		return nil, false
	}
	return o.AriaLabel, true
}

// HasAriaLabel returns a boolean if a field has been set.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink) HasAriaLabel() bool {
	if o != nil && !IsNil(o.AriaLabel) {
		return true
	}

	return false
}

// SetAriaLabel gets a reference to the given string and assigns it to the AriaLabel field.
func (o *ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink) SetAriaLabel(v string) {
	o.AriaLabel = &v
}

func (o ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if !IsNil(o.AriaLabel) {
		toSerialize["ariaLabel"] = o.AriaLabel
	}
	return toSerialize, nil
}

type NullableApiCampaignsGet200ResponseDataItemsInnerContentDetailLink struct {
	value *ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink
	isSet bool
}

func (v NullableApiCampaignsGet200ResponseDataItemsInnerContentDetailLink) Get() *ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink {
	return v.value
}

func (v *NullableApiCampaignsGet200ResponseDataItemsInnerContentDetailLink) Set(val *ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCampaignsGet200ResponseDataItemsInnerContentDetailLink) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCampaignsGet200ResponseDataItemsInnerContentDetailLink) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCampaignsGet200ResponseDataItemsInnerContentDetailLink(val *ApiCampaignsGet200ResponseDataItemsInnerContentDetailLink) *NullableApiCampaignsGet200ResponseDataItemsInnerContentDetailLink {
	return &NullableApiCampaignsGet200ResponseDataItemsInnerContentDetailLink{value: val, isSet: true}
}

func (v NullableApiCampaignsGet200ResponseDataItemsInnerContentDetailLink) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCampaignsGet200ResponseDataItemsInnerContentDetailLink) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


