/*
secure.scotiabank.com.har Mitmproxy2Swagger

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiRewardsRewardIdGet200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiRewardsRewardIdGet200ResponseData{}

// ApiRewardsRewardIdGet200ResponseData struct for ApiRewardsRewardIdGet200ResponseData
type ApiRewardsRewardIdGet200ResponseData struct {
	RewardType *string `json:"rewardType,omitempty"`
	PortfolioBalance *float32 `json:"portfolioBalance,omitempty"`
	AccountKey *string `json:"accountKey,omitempty"`
	SceneNumber *string `json:"sceneNumber,omitempty"`
	ProgramName *string `json:"programName,omitempty"`
	Accounts []ApiRewardsRewardIdGet200ResponseDataAccountsInner `json:"accounts,omitempty"`
}

// NewApiRewardsRewardIdGet200ResponseData instantiates a new ApiRewardsRewardIdGet200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiRewardsRewardIdGet200ResponseData() *ApiRewardsRewardIdGet200ResponseData {
	this := ApiRewardsRewardIdGet200ResponseData{}
	return &this
}

// NewApiRewardsRewardIdGet200ResponseDataWithDefaults instantiates a new ApiRewardsRewardIdGet200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiRewardsRewardIdGet200ResponseDataWithDefaults() *ApiRewardsRewardIdGet200ResponseData {
	this := ApiRewardsRewardIdGet200ResponseData{}
	return &this
}

// GetRewardType returns the RewardType field value if set, zero value otherwise.
func (o *ApiRewardsRewardIdGet200ResponseData) GetRewardType() string {
	if o == nil || IsNil(o.RewardType) {
		var ret string
		return ret
	}
	return *o.RewardType
}

// GetRewardTypeOk returns a tuple with the RewardType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiRewardsRewardIdGet200ResponseData) GetRewardTypeOk() (*string, bool) {
	if o == nil || IsNil(o.RewardType) {
		return nil, false
	}
	return o.RewardType, true
}

// HasRewardType returns a boolean if a field has been set.
func (o *ApiRewardsRewardIdGet200ResponseData) HasRewardType() bool {
	if o != nil && !IsNil(o.RewardType) {
		return true
	}

	return false
}

// SetRewardType gets a reference to the given string and assigns it to the RewardType field.
func (o *ApiRewardsRewardIdGet200ResponseData) SetRewardType(v string) {
	o.RewardType = &v
}

// GetPortfolioBalance returns the PortfolioBalance field value if set, zero value otherwise.
func (o *ApiRewardsRewardIdGet200ResponseData) GetPortfolioBalance() float32 {
	if o == nil || IsNil(o.PortfolioBalance) {
		var ret float32
		return ret
	}
	return *o.PortfolioBalance
}

// GetPortfolioBalanceOk returns a tuple with the PortfolioBalance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiRewardsRewardIdGet200ResponseData) GetPortfolioBalanceOk() (*float32, bool) {
	if o == nil || IsNil(o.PortfolioBalance) {
		return nil, false
	}
	return o.PortfolioBalance, true
}

// HasPortfolioBalance returns a boolean if a field has been set.
func (o *ApiRewardsRewardIdGet200ResponseData) HasPortfolioBalance() bool {
	if o != nil && !IsNil(o.PortfolioBalance) {
		return true
	}

	return false
}

// SetPortfolioBalance gets a reference to the given float32 and assigns it to the PortfolioBalance field.
func (o *ApiRewardsRewardIdGet200ResponseData) SetPortfolioBalance(v float32) {
	o.PortfolioBalance = &v
}

// GetAccountKey returns the AccountKey field value if set, zero value otherwise.
func (o *ApiRewardsRewardIdGet200ResponseData) GetAccountKey() string {
	if o == nil || IsNil(o.AccountKey) {
		var ret string
		return ret
	}
	return *o.AccountKey
}

// GetAccountKeyOk returns a tuple with the AccountKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiRewardsRewardIdGet200ResponseData) GetAccountKeyOk() (*string, bool) {
	if o == nil || IsNil(o.AccountKey) {
		return nil, false
	}
	return o.AccountKey, true
}

// HasAccountKey returns a boolean if a field has been set.
func (o *ApiRewardsRewardIdGet200ResponseData) HasAccountKey() bool {
	if o != nil && !IsNil(o.AccountKey) {
		return true
	}

	return false
}

// SetAccountKey gets a reference to the given string and assigns it to the AccountKey field.
func (o *ApiRewardsRewardIdGet200ResponseData) SetAccountKey(v string) {
	o.AccountKey = &v
}

// GetSceneNumber returns the SceneNumber field value if set, zero value otherwise.
func (o *ApiRewardsRewardIdGet200ResponseData) GetSceneNumber() string {
	if o == nil || IsNil(o.SceneNumber) {
		var ret string
		return ret
	}
	return *o.SceneNumber
}

// GetSceneNumberOk returns a tuple with the SceneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiRewardsRewardIdGet200ResponseData) GetSceneNumberOk() (*string, bool) {
	if o == nil || IsNil(o.SceneNumber) {
		return nil, false
	}
	return o.SceneNumber, true
}

// HasSceneNumber returns a boolean if a field has been set.
func (o *ApiRewardsRewardIdGet200ResponseData) HasSceneNumber() bool {
	if o != nil && !IsNil(o.SceneNumber) {
		return true
	}

	return false
}

// SetSceneNumber gets a reference to the given string and assigns it to the SceneNumber field.
func (o *ApiRewardsRewardIdGet200ResponseData) SetSceneNumber(v string) {
	o.SceneNumber = &v
}

// GetProgramName returns the ProgramName field value if set, zero value otherwise.
func (o *ApiRewardsRewardIdGet200ResponseData) GetProgramName() string {
	if o == nil || IsNil(o.ProgramName) {
		var ret string
		return ret
	}
	return *o.ProgramName
}

// GetProgramNameOk returns a tuple with the ProgramName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiRewardsRewardIdGet200ResponseData) GetProgramNameOk() (*string, bool) {
	if o == nil || IsNil(o.ProgramName) {
		return nil, false
	}
	return o.ProgramName, true
}

// HasProgramName returns a boolean if a field has been set.
func (o *ApiRewardsRewardIdGet200ResponseData) HasProgramName() bool {
	if o != nil && !IsNil(o.ProgramName) {
		return true
	}

	return false
}

// SetProgramName gets a reference to the given string and assigns it to the ProgramName field.
func (o *ApiRewardsRewardIdGet200ResponseData) SetProgramName(v string) {
	o.ProgramName = &v
}

// GetAccounts returns the Accounts field value if set, zero value otherwise.
func (o *ApiRewardsRewardIdGet200ResponseData) GetAccounts() []ApiRewardsRewardIdGet200ResponseDataAccountsInner {
	if o == nil || IsNil(o.Accounts) {
		var ret []ApiRewardsRewardIdGet200ResponseDataAccountsInner
		return ret
	}
	return o.Accounts
}

// GetAccountsOk returns a tuple with the Accounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiRewardsRewardIdGet200ResponseData) GetAccountsOk() ([]ApiRewardsRewardIdGet200ResponseDataAccountsInner, bool) {
	if o == nil || IsNil(o.Accounts) {
		return nil, false
	}
	return o.Accounts, true
}

// HasAccounts returns a boolean if a field has been set.
func (o *ApiRewardsRewardIdGet200ResponseData) HasAccounts() bool {
	if o != nil && !IsNil(o.Accounts) {
		return true
	}

	return false
}

// SetAccounts gets a reference to the given []ApiRewardsRewardIdGet200ResponseDataAccountsInner and assigns it to the Accounts field.
func (o *ApiRewardsRewardIdGet200ResponseData) SetAccounts(v []ApiRewardsRewardIdGet200ResponseDataAccountsInner) {
	o.Accounts = v
}

func (o ApiRewardsRewardIdGet200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiRewardsRewardIdGet200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RewardType) {
		toSerialize["rewardType"] = o.RewardType
	}
	if !IsNil(o.PortfolioBalance) {
		toSerialize["portfolioBalance"] = o.PortfolioBalance
	}
	if !IsNil(o.AccountKey) {
		toSerialize["accountKey"] = o.AccountKey
	}
	if !IsNil(o.SceneNumber) {
		toSerialize["sceneNumber"] = o.SceneNumber
	}
	if !IsNil(o.ProgramName) {
		toSerialize["programName"] = o.ProgramName
	}
	if !IsNil(o.Accounts) {
		toSerialize["accounts"] = o.Accounts
	}
	return toSerialize, nil
}

type NullableApiRewardsRewardIdGet200ResponseData struct {
	value *ApiRewardsRewardIdGet200ResponseData
	isSet bool
}

func (v NullableApiRewardsRewardIdGet200ResponseData) Get() *ApiRewardsRewardIdGet200ResponseData {
	return v.value
}

func (v *NullableApiRewardsRewardIdGet200ResponseData) Set(val *ApiRewardsRewardIdGet200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableApiRewardsRewardIdGet200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableApiRewardsRewardIdGet200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiRewardsRewardIdGet200ResponseData(val *ApiRewardsRewardIdGet200ResponseData) *NullableApiRewardsRewardIdGet200ResponseData {
	return &NullableApiRewardsRewardIdGet200ResponseData{value: val, isSet: true}
}

func (v NullableApiRewardsRewardIdGet200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiRewardsRewardIdGet200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


