/*
secure.scotiabank.com.har Mitmproxy2Swagger

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiCampaignsGet200ResponseDataItemsInnerExternalRef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCampaignsGet200ResponseDataItemsInnerExternalRef{}

// ApiCampaignsGet200ResponseDataItemsInnerExternalRef struct for ApiCampaignsGet200ResponseDataItemsInnerExternalRef
type ApiCampaignsGet200ResponseDataItemsInnerExternalRef struct {
	CampaignId *string `json:"campaignId,omitempty"`
	MessageId *string `json:"messageId,omitempty"`
	MessageSource *string `json:"messageSource,omitempty"`
}

// NewApiCampaignsGet200ResponseDataItemsInnerExternalRef instantiates a new ApiCampaignsGet200ResponseDataItemsInnerExternalRef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCampaignsGet200ResponseDataItemsInnerExternalRef() *ApiCampaignsGet200ResponseDataItemsInnerExternalRef {
	this := ApiCampaignsGet200ResponseDataItemsInnerExternalRef{}
	return &this
}

// NewApiCampaignsGet200ResponseDataItemsInnerExternalRefWithDefaults instantiates a new ApiCampaignsGet200ResponseDataItemsInnerExternalRef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCampaignsGet200ResponseDataItemsInnerExternalRefWithDefaults() *ApiCampaignsGet200ResponseDataItemsInnerExternalRef {
	this := ApiCampaignsGet200ResponseDataItemsInnerExternalRef{}
	return &this
}

// GetCampaignId returns the CampaignId field value if set, zero value otherwise.
func (o *ApiCampaignsGet200ResponseDataItemsInnerExternalRef) GetCampaignId() string {
	if o == nil || IsNil(o.CampaignId) {
		var ret string
		return ret
	}
	return *o.CampaignId
}

// GetCampaignIdOk returns a tuple with the CampaignId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCampaignsGet200ResponseDataItemsInnerExternalRef) GetCampaignIdOk() (*string, bool) {
	if o == nil || IsNil(o.CampaignId) {
		return nil, false
	}
	return o.CampaignId, true
}

// HasCampaignId returns a boolean if a field has been set.
func (o *ApiCampaignsGet200ResponseDataItemsInnerExternalRef) HasCampaignId() bool {
	if o != nil && !IsNil(o.CampaignId) {
		return true
	}

	return false
}

// SetCampaignId gets a reference to the given string and assigns it to the CampaignId field.
func (o *ApiCampaignsGet200ResponseDataItemsInnerExternalRef) SetCampaignId(v string) {
	o.CampaignId = &v
}

// GetMessageId returns the MessageId field value if set, zero value otherwise.
func (o *ApiCampaignsGet200ResponseDataItemsInnerExternalRef) GetMessageId() string {
	if o == nil || IsNil(o.MessageId) {
		var ret string
		return ret
	}
	return *o.MessageId
}

// GetMessageIdOk returns a tuple with the MessageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCampaignsGet200ResponseDataItemsInnerExternalRef) GetMessageIdOk() (*string, bool) {
	if o == nil || IsNil(o.MessageId) {
		return nil, false
	}
	return o.MessageId, true
}

// HasMessageId returns a boolean if a field has been set.
func (o *ApiCampaignsGet200ResponseDataItemsInnerExternalRef) HasMessageId() bool {
	if o != nil && !IsNil(o.MessageId) {
		return true
	}

	return false
}

// SetMessageId gets a reference to the given string and assigns it to the MessageId field.
func (o *ApiCampaignsGet200ResponseDataItemsInnerExternalRef) SetMessageId(v string) {
	o.MessageId = &v
}

// GetMessageSource returns the MessageSource field value if set, zero value otherwise.
func (o *ApiCampaignsGet200ResponseDataItemsInnerExternalRef) GetMessageSource() string {
	if o == nil || IsNil(o.MessageSource) {
		var ret string
		return ret
	}
	return *o.MessageSource
}

// GetMessageSourceOk returns a tuple with the MessageSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCampaignsGet200ResponseDataItemsInnerExternalRef) GetMessageSourceOk() (*string, bool) {
	if o == nil || IsNil(o.MessageSource) {
		return nil, false
	}
	return o.MessageSource, true
}

// HasMessageSource returns a boolean if a field has been set.
func (o *ApiCampaignsGet200ResponseDataItemsInnerExternalRef) HasMessageSource() bool {
	if o != nil && !IsNil(o.MessageSource) {
		return true
	}

	return false
}

// SetMessageSource gets a reference to the given string and assigns it to the MessageSource field.
func (o *ApiCampaignsGet200ResponseDataItemsInnerExternalRef) SetMessageSource(v string) {
	o.MessageSource = &v
}

func (o ApiCampaignsGet200ResponseDataItemsInnerExternalRef) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCampaignsGet200ResponseDataItemsInnerExternalRef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CampaignId) {
		toSerialize["campaignId"] = o.CampaignId
	}
	if !IsNil(o.MessageId) {
		toSerialize["messageId"] = o.MessageId
	}
	if !IsNil(o.MessageSource) {
		toSerialize["messageSource"] = o.MessageSource
	}
	return toSerialize, nil
}

type NullableApiCampaignsGet200ResponseDataItemsInnerExternalRef struct {
	value *ApiCampaignsGet200ResponseDataItemsInnerExternalRef
	isSet bool
}

func (v NullableApiCampaignsGet200ResponseDataItemsInnerExternalRef) Get() *ApiCampaignsGet200ResponseDataItemsInnerExternalRef {
	return v.value
}

func (v *NullableApiCampaignsGet200ResponseDataItemsInnerExternalRef) Set(val *ApiCampaignsGet200ResponseDataItemsInnerExternalRef) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCampaignsGet200ResponseDataItemsInnerExternalRef) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCampaignsGet200ResponseDataItemsInnerExternalRef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCampaignsGet200ResponseDataItemsInnerExternalRef(val *ApiCampaignsGet200ResponseDataItemsInnerExternalRef) *NullableApiCampaignsGet200ResponseDataItemsInnerExternalRef {
	return &NullableApiCampaignsGet200ResponseDataItemsInnerExternalRef{value: val, isSet: true}
}

func (v NullableApiCampaignsGet200ResponseDataItemsInnerExternalRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCampaignsGet200ResponseDataItemsInnerExternalRef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


