/*
secure.scotiabank.com.har Mitmproxy2Swagger

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiAccountsSummaryGet200ResponseDataTotalBalancesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAccountsSummaryGet200ResponseDataTotalBalancesInner{}

// ApiAccountsSummaryGet200ResponseDataTotalBalancesInner struct for ApiAccountsSummaryGet200ResponseDataTotalBalancesInner
type ApiAccountsSummaryGet200ResponseDataTotalBalancesInner struct {
	ProductCategory *string `json:"productCategory,omitempty"`
	Retail []ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner `json:"retail,omitempty"`
}

// NewApiAccountsSummaryGet200ResponseDataTotalBalancesInner instantiates a new ApiAccountsSummaryGet200ResponseDataTotalBalancesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAccountsSummaryGet200ResponseDataTotalBalancesInner() *ApiAccountsSummaryGet200ResponseDataTotalBalancesInner {
	this := ApiAccountsSummaryGet200ResponseDataTotalBalancesInner{}
	return &this
}

// NewApiAccountsSummaryGet200ResponseDataTotalBalancesInnerWithDefaults instantiates a new ApiAccountsSummaryGet200ResponseDataTotalBalancesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAccountsSummaryGet200ResponseDataTotalBalancesInnerWithDefaults() *ApiAccountsSummaryGet200ResponseDataTotalBalancesInner {
	this := ApiAccountsSummaryGet200ResponseDataTotalBalancesInner{}
	return &this
}

// GetProductCategory returns the ProductCategory field value if set, zero value otherwise.
func (o *ApiAccountsSummaryGet200ResponseDataTotalBalancesInner) GetProductCategory() string {
	if o == nil || IsNil(o.ProductCategory) {
		var ret string
		return ret
	}
	return *o.ProductCategory
}

// GetProductCategoryOk returns a tuple with the ProductCategory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAccountsSummaryGet200ResponseDataTotalBalancesInner) GetProductCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.ProductCategory) {
		return nil, false
	}
	return o.ProductCategory, true
}

// HasProductCategory returns a boolean if a field has been set.
func (o *ApiAccountsSummaryGet200ResponseDataTotalBalancesInner) HasProductCategory() bool {
	if o != nil && !IsNil(o.ProductCategory) {
		return true
	}

	return false
}

// SetProductCategory gets a reference to the given string and assigns it to the ProductCategory field.
func (o *ApiAccountsSummaryGet200ResponseDataTotalBalancesInner) SetProductCategory(v string) {
	o.ProductCategory = &v
}

// GetRetail returns the Retail field value if set, zero value otherwise.
func (o *ApiAccountsSummaryGet200ResponseDataTotalBalancesInner) GetRetail() []ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner {
	if o == nil || IsNil(o.Retail) {
		var ret []ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner
		return ret
	}
	return o.Retail
}

// GetRetailOk returns a tuple with the Retail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAccountsSummaryGet200ResponseDataTotalBalancesInner) GetRetailOk() ([]ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner, bool) {
	if o == nil || IsNil(o.Retail) {
		return nil, false
	}
	return o.Retail, true
}

// HasRetail returns a boolean if a field has been set.
func (o *ApiAccountsSummaryGet200ResponseDataTotalBalancesInner) HasRetail() bool {
	if o != nil && !IsNil(o.Retail) {
		return true
	}

	return false
}

// SetRetail gets a reference to the given []ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner and assigns it to the Retail field.
func (o *ApiAccountsSummaryGet200ResponseDataTotalBalancesInner) SetRetail(v []ApiAccountsSummaryGet200ResponseDataProductsInnerPrimaryBalancesInner) {
	o.Retail = v
}

func (o ApiAccountsSummaryGet200ResponseDataTotalBalancesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAccountsSummaryGet200ResponseDataTotalBalancesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProductCategory) {
		toSerialize["productCategory"] = o.ProductCategory
	}
	if !IsNil(o.Retail) {
		toSerialize["retail"] = o.Retail
	}
	return toSerialize, nil
}

type NullableApiAccountsSummaryGet200ResponseDataTotalBalancesInner struct {
	value *ApiAccountsSummaryGet200ResponseDataTotalBalancesInner
	isSet bool
}

func (v NullableApiAccountsSummaryGet200ResponseDataTotalBalancesInner) Get() *ApiAccountsSummaryGet200ResponseDataTotalBalancesInner {
	return v.value
}

func (v *NullableApiAccountsSummaryGet200ResponseDataTotalBalancesInner) Set(val *ApiAccountsSummaryGet200ResponseDataTotalBalancesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAccountsSummaryGet200ResponseDataTotalBalancesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAccountsSummaryGet200ResponseDataTotalBalancesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAccountsSummaryGet200ResponseDataTotalBalancesInner(val *ApiAccountsSummaryGet200ResponseDataTotalBalancesInner) *NullableApiAccountsSummaryGet200ResponseDataTotalBalancesInner {
	return &NullableApiAccountsSummaryGet200ResponseDataTotalBalancesInner{value: val, isSet: true}
}

func (v NullableApiAccountsSummaryGet200ResponseDataTotalBalancesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAccountsSummaryGet200ResponseDataTotalBalancesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


